# PROJECT TITLE:
# Cross-Country Analysis of Economic Growth Trends Using GDP (Current US$) Data, 1970–2024
## Problem Statement: 
## To perform a descriptive analysis of country-wise GDP (Current US$) from 1970 to 2024 by studying long-term growth trends, computing annual and average growth rates, comparing economic performance across countries, analyzing growth fluctuations over decades, and identifying relative economic progression among nations.

### Creating a virtual environment with every required libraries installed in it.
python -m venv .venv

#### Activating it
.venv/Scripts/Activate

# Cross-Country Analysis of Economic Growth Trends (1970–2024)

## Phase 1: Data Understanding, Preprocessing & Feature Engineering

### Current Progress
- Created isolated virtual environment and installed required analytical libraries
- Loaded the dataset into a working DataFrame
- Performed initial structural inspection using:
  - `.head()`
  - `.shape`
  - `.columns`
  - `.info()`
  - Missing value summary
- Identified presence of multiple economic indicators within the dataset

### Objectives of This Phase
1. Validate and filter dataset to retain only GDP (Current US$) indicator  
2. Verify data structure consistency (one row per country)  
3. Examine data types and descriptive statistics  
4. Analyze missing value distribution across years  
5. Apply appropriate data cleaning techniques  
6. Prepare dataset in wide format for:
   - Annual growth rate computation  
   - Average growth calculation  
   - Growth volatility analysis  
   - Decade-wise economic comparison  

### Expected Output of Phase 1
A cleaned, structured, GDP-only dataset ready for descriptive cross-country economic analysis.

## Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import zscore
from sklearn.preprocessing import StandardScaler

#### Before performing manipulations in Python, I deleted the first two rows from the dataset because they were not needed.

## Loading the Dataset

In [2]:
# Load dataset
file_path = r"C:\Projects\DAP\gdp-growth-analysis\data\GDPcurrent-USD-countries.xlsx"
df_raw = pd.read_excel(file_path)

# Create working copy
df = df_raw.copy()

df.head()

,CountryID,Country,IndicatorName,1970,1971,1972,1973,1974,1975,1976,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,4,Afghanistan,Final consumption expenditure,1.691109e+09,1.826664e+09,1.544444e+09,1.637778e+09,1.984444e+09,2.173333e+09,2.248889e+09,...,1.905434e+10,1.841552e+10,1.859587e+10,2.082703e+10,2.138090e+10,2.286309e+10,1.663770e+10,1.693301e+10,2.009309e+10,2.708702e+10
1,4,Afghanistan,Household consumption expenditure (including N...,1.577102e+09,1.703519e+09,1.440325e+09,1.527366e+09,1.850662e+09,2.026817e+09,2.097279e+09,...,1.496906e+10,1.429584e+10,1.460787e+10,1.688326e+10,1.721976e+10,1.844500e+10,1.341413e+10,1.383642e+10,1.662669e+10,2.212882e+10
2,4,Afghanistan,General government final consumption expenditure,1.140071e+08,1.231456e+08,1.041196e+08,1.104117e+08,1.337824e+08,1.465165e+08,1.516101e+08,...,4.085273e+09,4.119686e+09,3.987993e+09,3.943771e+09,4.161138e+09,4.418088e+09,3.223572e+09,3.096592e+09,3.466403e+09,4.958199e+09
3,4,Afghanistan,Gross capital formation,9.555556e+07,9.999998e+07,1.044445e+08,1.266666e+08,1.888889e+08,2.311111e+08,3.488889e+08,...,2.711463e+09,2.331712e+09,2.640511e+09,2.689519e+09,2.434404e+09,2.289180e+09,1.968903e+09,2.362752e+09,2.490757e+09,2.041052e+09
4,4,Afghanistan,Gross fixed capital formation (including Acqui...,9.555556e+07,9.999998e+07,1.044445e+08,1.266666e+08,1.888889e+08,2.311111e+08,3.488889e+08,...,2.711463e+09,2.331712e+09,2.640511e+09,2.689519e+09,2.434404e+09,2.289180e+09,1.968903e+09,2.362752e+09,2.490757e+09,2.041052e+09

## Data Overview & Structure Inspection

In [3]:
print("Shape of dataset:", df.shape)
print("\nColumn Names:")
print(df.columns)

print("\nDataset Info:")
df.info()

print("\nMissing Values per Column:")
print(df.isna().sum())

Shape of dataset: (3715, 58)

Column Names:
Index([    'CountryID',       'Country', 'IndicatorName',            1970,
                  1971,            1972,            1973,            1974,
                  1975,            1976,            1977,            1978,
                  1979,            1980,            1981,            1982,
                  1983,            1984,            1985,            1986,
                  1987,            1988,            1989,            1990,
                  1991,            1992,            1993,            1994,
                  1995,            1996,            1997,            1998,
                  1999,            2000,            2001,            2002,
                  2003,            2004,            2005,            2006,
                  2007,            2008,            2009,            2010,
                  2011,            2012,            2013,            2014,
                  2015,            2016,            2017,            2018,
                  2019,            2020,            2021,            2022,
                  2023,            2024],
      dtype='object')

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3715 entries, 0 to 3714
Data columns (total 58 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryID      3715 non-null   int64
 1   Country        3715 non-null   object
 2   IndicatorName  3715 non-null   object
 3   1970           3122 non-null   float64
 4   1971           3122 non-null   float64
 5   1972           3123 non-null   float64
 6   1973           3125 non-null   float64
 7   1974           3123 non-null   float64
 8   1975           3125 non-null   float64
 9   1976           3124 non-null   float64
 10  1977           3124 non-null   float64
 11  1978           3124 non-null   float64
 12  1979           3127 non-null   float64
 13  1980           3128 non-null   float64
 14  1981           3129 non-null   float64
 15  1982           3130 non-null   float64
 16  1983           3130 non-null   float64
 17  1984           3131 non-null   float64
 18  1985           3133 non-null   float64
 19  1986           3132 non-null   float64
 20  1987           3136 non-null   float64
 21  1988           3136 non-null   float64
 22  1989           3152 non-null   float64
 23  1990           3624 non-null   float64
 24  1991           3543 non-null   float64
 25  1992           3538 non-null   float64
 26  1993           3541 non-null   float64
 27  1994           3525 non-null   float64
 28  1995           3526 non-null   float64
 29  1996           3526 non-null   float64
 30  1997           3527 non-null   float64
 31  1998           3523 non-null   float64
 32  1999           3523 non-null   float64
 33  2000           3525 non-null   float64
 34  2001           3527 non-null   float64
 35  2002           3530 non-null   float64
 36  2003           3529 non-null   float64
 37  2004           3534 non-null   float64
 38  2005           3565 non-null   float64
 39  2006           3567 non-null   float64
 40  2007           3566 non-null   float64
 41  2008           3599 non-null   float64
 42  2009           3597 non-null   float64
 43  2010           3596 non-null   float64
 44  2011           3580 non-null   float64
 45  2012           3579 non-null   float64
 46  2013           3561 non-null   float64
 47  2014           3560 non-null   float64
 48  2015           3561 non-null   float64
 49  2016           3561 non-null   float64
 50  2017           3560 non-null   float64
 51  2018           3560 non-null   float64
 52  2019           3561 non-null   float64
 53  2020           3560 non-null   float64
 54  2021           3558 non-null   float64
 55  2022           3557 non-null   float64
 56  2023           3556 non-null   float64
 57  2024           3550 non-null   float64
dtypes: float64(55), int64(1), object(2)
memory usage: 1.6+ MB

Missing Values per Column:
CountryID          0
Country            0
IndicatorName      0
1970             593
1971             593
1972             592
1973             590
1974             592
1975             590
1976             591
1977             591
1978             591
1979             588
1980             587
1981             586
1982             585
1983             585
1984             584
1985             582
1986             583
1987             579
1988             579
1989             563
1990              91
1991             172
1992             177
1993             174
1994             190
1995             189
1996             189
1997             188
1998             192
1999             192
2000             190
2001             188
2002             185
2003             186
2004             181
2005             150
2006             148
2007             149
2008             116
2009             118
2010             119
2011             135
2012             136
2013             154
2014             155
2015             154
2016             154
2017             155
2018             155
2019             154
2020             155
2021             157
2022             158
2023             159
2024             165
dtype: int64

### Accessing Indicators Name

In [4]:
print("Unique Indicators:")
print(df["IndicatorName"].unique())

Unique Indicators:
['Final consumption expenditure'
 'Household consumption expenditure (including Non-profit institutions serving households)'
 'General government final consumption expenditure'
 'Gross capital formation'
 'Gross fixed capital formation (including Acquisitions less disposals of valuables)'
 'Exports of goods and services' 'Imports of goods and services'
 'Gross Domestic Product (GDP)'
 'Agriculture, hunting, forestry, fishing (ISIC A-B)'
 'Mining, Manufacturing, Utilities (ISIC C-E)' 'Manufacturing (ISIC D)'
 'Construction (ISIC F)'
 'Wholesale, retail trade, restaurants and hotels (ISIC G-H)'
 'Transport, storage and communication (ISIC I)'
 'Other Activities (ISIC J-P)' 'Total Value Added'
 'Changes in inventories']

In [5]:
df_gdp = df[df["IndicatorName"].str.contains("GDP", case=False)]

df_gdp.head()

,CountryID,Country,IndicatorName,1970,1971,1972,1973,1974,1975,1976,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
7,4,Afghanistan,Gross Domestic Product (GDP),1.748887e+09,1.831109e+09,1.595555e+09,1.733333e+09,2.155556e+09,2.366667e+09,2.555556e+09,...,1.869957e+10,1.822435e+10,1.903430e+10,1.885632e+10,1.937236e+10,1.998301e+10,1.516092e+10,1.417499e+10,1.633976e+10,1.828316e+10
24,8,Albania,Gross Domestic Product (GDP),2.265577e+09,2.330585e+09,2.397526e+09,2.466543e+09,2.537016e+09,2.610110e+09,2.685746e+09,...,1.147017e+10,1.198867e+10,1.325824e+10,1.537951e+10,1.558511e+10,1.524146e+10,1.803199e+10,1.901725e+10,2.349124e+10,2.703747e+10
41,12,Algeria,Gross Domestic Product (GDP),5.155121e+09,5.363676e+09,7.176428e+09,9.229622e+09,1.325976e+10,1.555555e+10,1.775003e+10,...,1.874939e+11,1.807638e+11,1.898809e+11,1.945545e+11,1.934597e+11,1.648734e+11,1.862317e+11,2.256385e+11,2.476262e+11,2.669723e+11
58,20,Andorra,Gross Domestic Product (GDP),9.947679e+07,1.131285e+08,1.435060e+08,1.908638e+08,2.360555e+08,2.785143e+08,2.875884e+08,...,2.789880e+09,2.896613e+09,3.000160e+09,3.218419e+09,3.155152e+09,2.890998e+09,3.324642e+09,3.380613e+09,3.785063e+09,4.039838e+09
75,24,Angola,Gross Domestic Product (GDP),3.806982e+09,4.007445e+09,4.102155e+09,5.016276e+09,5.626961e+09,4.147433e+09,3.980907e+09,...,1.316610e+11,1.147637e+11,1.398346e+11,1.141892e+11,9.467123e+10,6.652065e+10,8.437511e+10,1.424029e+11,1.143358e+11,1.171594e+11

In [6]:
print("Shape after GDP filter:", df_gdp.shape)

Shape after GDP filter: (220, 58)

In [7]:
df_gdp.dtypes

CountryID          int64
Country           object
IndicatorName     object
1970             float64
1971             float64
1972             float64
1973             float64
1974             float64
1975             float64
1976             float64
1977             float64
1978             float64
1979             float64
1980             float64
1981             float64
1982             float64
1983             float64
1984             float64
1985             float64
1986             float64
1987             float64
1988             float64
1989             float64
1990             float64
1991             float64
1992             float64
1993             float64
1994             float64
1995             float64
1996             float64
1997             float64
1998             float64
1999             float64
2000             float64
2001             float64
2002             float64
2003             float64
2004             float64
2005             float64
2006             float64
2007             float64
2008             float64
2009             float64
2010             float64
2011             float64
2012             float64
2013             float64
2014             float64
2015             float64
2016             float64
2017             float64
2018             float64
2019             float64
2020             float64
2021             float64
2022             float64
2023             float64
2024             float64
dtype: object

In [8]:
df_gdp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 220 entries, 7 to 3706
Data columns (total 58 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryID      220 non-null    int64
 1   Country        220 non-null    object
 2   IndicatorName  220 non-null    object
 3   1970           187 non-null    float64
 4   1971           187 non-null    float64
 5   1972           187 non-null    float64
 6   1973           187 non-null    float64
 7   1974           187 non-null    float64
 8   1975           187 non-null    float64
 9   1976           187 non-null    float64
 10  1977           187 non-null    float64
 11  1978           187 non-null    float64
 12  1979           187 non-null    float64
 13  1980           187 non-null    float64
 14  1981           187 non-null    float64
 15  1982           187 non-null    float64
 16  1983           187 non-null    float64
 17  1984           187 non-null    float64
 18  1985           187 non-null    float64
 19  1986           187 non-null    float64
 20  1987           187 non-null    float64
 21  1988           187 non-null    float64
 22  1989           188 non-null    float64
 23  1990           216 non-null    float64
 24  1991           211 non-null    float64
 25  1992           211 non-null    float64
 26  1993           211 non-null    float64
 27  1994           210 non-null    float64
 28  1995           210 non-null    float64
 29  1996           210 non-null    float64
 30  1997           210 non-null    float64
 31  1998           210 non-null    float64
 32  1999           210 non-null    float64
 33  2000           210 non-null    float64
 34  2001           210 non-null    float64
 35  2002           210 non-null    float64
 36  2003           210 non-null    float64
 37  2004           210 non-null    float64
 38  2005           212 non-null    float64
 39  2006           212 non-null    float64
 40  2007           212 non-null    float64
 41  2008           214 non-null    float64
 42  2009           214 non-null    float64
 43  2010           214 non-null    float64
 44  2011           213 non-null    float64
 45  2012           213 non-null    float64
 46  2013           212 non-null    float64
 47  2014           212 non-null    float64
 48  2015           212 non-null    float64
 49  2016           212 non-null    float64
 50  2017           212 non-null    float64
 51  2018           212 non-null    float64
 52  2019           212 non-null    float64
 53  2020           212 non-null    float64
 54  2021           212 non-null    float64
 55  2022           212 non-null    float64
 56  2023           212 non-null    float64
 57  2024           212 non-null    float64
dtypes: float64(55), int64(1), object(2)
memory usage: 101.4+ KB

### Extracting year-wise columns from the dataset and generating descriptive statistics.

In [9]:
year_columns = [col for col in df_gdp.columns if str(col).isdigit()]

df_gdp[year_columns].describe()

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
count,1.870000e+02,1.870000e+02,1.870000e+02,1.870000e+02,1.870000e+02,1.870000e+02,1.870000e+02,1.870000e+02,1.870000e+02,1.870000e+02,...,2.120000e+02,2.120000e+02,2.120000e+02,2.120000e+02,2.120000e+02,2.120000e+02,2.120000e+02,2.120000e+02,2.120000e+02,2.120000e+02
mean,1.829734e+10,2.013764e+10,2.317109e+10,2.819060e+10,3.193288e+10,3.571391e+10,3.858786e+10,4.344857e+10,5.147409e+10,5.923482e+10,...,3.562585e+11,3.621300e+11,3.853496e+11,4.092343e+11,4.151454e+11,4.044198e+11,4.620231e+11,4.807423e+11,5.021776e+11,5.224912e+11
std,8.866019e+10,9.628708e+10,1.075792e+11,1.239086e+11,1.336752e+11,1.470199e+11,1.606235e+11,1.796533e+11,2.098045e+11,2.344635e+11,...,1.555933e+12,1.597216e+12,1.685309e+12,1.806712e+12,1.868176e+12,1.868927e+12,2.132042e+12,2.254208e+12,2.356668e+12,2.460942e+12
min,2.585174e+06,2.747866e+06,3.028236e+06,3.780359e+06,4.013522e+06,3.847741e+06,3.797642e+06,3.546258e+06,3.853304e+06,3.998563e+06,...,3.619381e+07,4.130612e+07,4.528888e+07,4.816892e+07,5.378957e+07,5.246941e+07,6.145732e+07,5.418711e+07,5.054876e+07,5.643602e+07
25%,2.194021e+08,2.445365e+08,2.850735e+08,3.614351e+08,4.097892e+08,4.928473e+08,5.305898e+08,5.819454e+08,6.696585e+08,7.593423e+08,...,6.064012e+09,5.973133e+09,5.843874e+09,6.326665e+09,6.369348e+09,6.217613e+09,7.079508e+09,7.059586e+09,7.542800e+09,8.480262e+09
50%,1.067267e+09,1.213650e+09,1.300600e+09,1.605731e+09,2.127503e+09,2.398801e+09,2.680976e+09,2.791325e+09,3.098138e+09,3.697940e+09,...,2.337504e+10,2.390788e+10,2.546683e+10,2.667462e+10,2.759673e+10,2.541755e+10,3.093001e+10,3.179752e+10,3.486088e+10,3.690406e+10
75%,6.017784e+09,6.933917e+09,8.145223e+09,9.409526e+09,1.238624e+10,1.315209e+10,1.426080e+10,1.602731e+10,1.834957e+10,2.238019e+10,...,1.779699e+11,1.701428e+11,1.878835e+11,1.966976e+11,1.846153e+11,1.664257e+11,1.977757e+11,2.255319e+11,2.445303e+11,2.533489e+11
max,1.073303e+12,1.164850e+12,1.279110e+12,1.425376e+12,1.545243e+12,1.684904e+12,1.873412e+12,2.081826e+12,2.351599e+12,2.627333e+12,...,1.829502e+13,1.880491e+13,1.961210e+13,2.065652e+13,2.154000e+13,2.137530e+13,2.372560e+13,2.605460e+13,2.781150e+13,2.929800e+13

### Missing values in year columns sorted in ascending order.

In [10]:
missing_summary = df_gdp[year_columns].isna().sum()
missing_summary.sort_values(ascending=False).head(20)

1970    33
1971    33
1972    33
1973    33
1974    33
1975    33
1976    33
1977    33
1978    33
1979    33
1980    33
1981    33
1982    33
1983    33
1984    33
1985    33
1986    33
1987    33
1988    33
1989    32
dtype: int64

### Checking for duplicate country entries.

In [11]:
print("Duplicate countries:", df_gdp["Country"].duplicated().sum())

Duplicate countries: 0

### Filtering Exactly One GDP Indicator

In [12]:
print(df_gdp["IndicatorName"].unique())

['Gross Domestic Product (GDP)']

### Dropping Unnecessary Columns

In [13]:
df_gdp = df_gdp.drop(columns=["IndicatorName", "CountryID"])

In [14]:
df_gdp.head()

,Country,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
7,Afghanistan,1.748887e+09,1.831109e+09,1.595555e+09,1.733333e+09,2.155556e+09,2.366667e+09,2.555556e+09,2.953333e+09,3.300000e+09,...,1.869957e+10,1.822435e+10,1.903430e+10,1.885632e+10,1.937236e+10,1.998301e+10,1.516092e+10,1.417499e+10,1.633976e+10,1.828316e+10
24,Albania,2.265577e+09,2.330585e+09,2.397526e+09,2.466543e+09,2.537016e+09,2.610110e+09,2.685746e+09,2.760746e+09,2.842276e+09,...,1.147017e+10,1.198867e+10,1.325824e+10,1.537951e+10,1.558511e+10,1.524146e+10,1.803199e+10,1.901725e+10,2.349124e+10,2.703747e+10
41,Algeria,5.155121e+09,5.363676e+09,7.176428e+09,9.229622e+09,1.325976e+10,1.555555e+10,1.775003e+10,2.099094e+10,2.637376e+10,...,1.874939e+11,1.807638e+11,1.898809e+11,1.945545e+11,1.934597e+11,1.648734e+11,1.862317e+11,2.256385e+11,2.476262e+11,2.669723e+11
58,Andorra,9.947679e+07,1.131285e+08,1.435060e+08,1.908638e+08,2.360555e+08,2.785143e+08,2.875884e+08,3.213901e+08,3.897459e+08,...,2.789880e+09,2.896613e+09,3.000160e+09,3.218419e+09,3.155152e+09,2.890998e+09,3.324642e+09,3.380613e+09,3.785063e+09,4.039838e+09
75,Angola,3.806982e+09,4.007445e+09,4.102155e+09,5.016276e+09,5.626961e+09,4.147433e+09,3.980907e+09,4.344225e+09,4.845482e+09,...,1.316610e+11,1.147637e+11,1.398346e+11,1.141892e+11,9.467123e+10,6.652065e+10,8.437511e+10,1.424029e+11,1.143358e+11,1.171594e+11

In [15]:
df_gdp.dtypes

Country     object
1970       float64
1971       float64
1972       float64
1973       float64
1974       float64
1975       float64
1976       float64
1977       float64
1978       float64
1979       float64
1980       float64
1981       float64
1982       float64
1983       float64
1984       float64
1985       float64
1986       float64
1987       float64
1988       float64
1989       float64
1990       float64
1991       float64
1992       float64
1993       float64
1994       float64
1995       float64
1996       float64
1997       float64
1998       float64
1999       float64
2000       float64
2001       float64
2002       float64
2003       float64
2004       float64
2005       float64
2006       float64
2007       float64
2008       float64
2009       float64
2010       float64
2011       float64
2012       float64
2013       float64
2014       float64
2015       float64
2016       float64
2017       float64
2018       float64
2019       float64
2020       float64
2021       float64
2022       float64
2023       float64
2024       float64
dtype: object

### Recalculating Year Columns

In [16]:
year_columns = [col for col in df_gdp.columns if str(col).isdigit()]
year_columns

[1970,
 1971,
 1972,
 1973,
 1974,
 1975,
 1976,
 1977,
 1978,
 1979,
 1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024]

### Country-Level Missing Analysis

In [17]:
df_gdp["Missing_Count"] = df_gdp[year_columns].isna().sum(axis=1)

df_gdp[["Country", "Missing_Count"]].sort_values(
    by="Missing_Count",
    ascending=False
).head()

                        Country  Missing_Count
3116                      Sudan             38
3031                South Sudan             38
871                     Curaçao             35
2930  Sint Maarten (Dutch part)             35
3638  Yemen Democratic (Former)             34

In [18]:
print("Total Countries:", len(df_gdp))
print("Countries with 0 missing:", (df_gdp["Missing_Count"] == 0).sum())
print("Countries with >10 missing:", (df_gdp["Missing_Count"] > 10).sum())

Total Countries: 220
Countries with 0 missing: 179
Countries with >10 missing: 41

In [19]:
df_gdp["Missing_Count"].describe()

count    220.000000
mean       4.327273
std        9.522968
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max       38.000000
Name: Missing_Count, dtype: float64

In [20]:
df_gdp_miss = df_gdp[df_gdp["Missing_Count"] >10]
df_gdp_miss.head()

,Country,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Missing_Count
141,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.054614e+10,1.152746e+10,1.245794e+10,1.361929e+10,1.264170e+10,1.387892e+10,1.951368e+10,2.418621e+10,2.595531e+10,20
209,Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.786701e+10,4.086663e+10,4.770071e+10,4.876247e+10,4.269300e+10,5.482541e+10,7.880747e+10,7.242847e+10,7.431588e+10,20
294,Belarus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.772355e+10,5.472542e+10,6.003102e+10,6.441016e+10,6.137167e+10,6.967377e+10,7.377516e+10,7.247875e+10,7.596188e+10,20
413,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.833506e+10,1.955367e+10,2.148883e+10,2.122189e+10,2.110432e+10,2.471100e+10,2.503274e+10,2.872706e+10,3.047810e+10,20
837,Croatia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.266149e+10,5.657333e+10,6.265750e+10,6.246713e+10,5.780932e+10,6.912083e+10,7.115420e+10,8.440431e+10,9.266241e+10,20

### Checking Missing Pattern by Year

In [21]:
df_gdp[year_columns].isna().sum().sort_values(ascending=False).head(25)

1970    33
1971    33
1972    33
1973    33
1974    33
1975    33
1976    33
1977    33
1978    33
1979    33
1980    33
1981    33
1982    33
1983    33
1984    33
1985    33
1986    33
1987    33
1988    33
1989    32
1996    10
1995    10
1994    10
2003    10
2002    10
dtype: int64

### Defining Analysis Period (1980 - 2024)
Early missing values are concentrated in post-independence or post-transition economies; therefore, analysis is restricted to 1980–2024 to ensure comparability and data reliability.

In [22]:
analysis_years = [y for y in range(1980, 2025)]
analysis_years = [y for y in analysis_years if y in df_gdp.columns]

In [23]:
analysis_years

[1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024]

### Checking missing values in this period

In [24]:
df_gdp["Missing_1980_2024"] = df_gdp[analysis_years].isna().sum(axis=1)

df_gdp["Missing_1980_2024"].describe()

count    220.000000
mean       2.827273
std        7.094096
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max       34.000000
Name: Missing_1980_2024, dtype: float64

In [25]:
df_gdp

,Country,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2017,2018,2019,2020,2021,2022,2023,2024,Missing_Count,Missing_1980_2024
7,Afghanistan,1.748887e+09,1.831109e+09,1.595555e+09,1.733333e+09,2.155556e+09,2.366667e+09,2.555556e+09,2.953333e+09,3.300000e+09,...,1.903430e+10,1.885632e+10,1.937236e+10,1.998301e+10,1.516092e+10,1.417499e+10,1.633976e+10,1.828316e+10,0,0
24,Albania,2.265577e+09,2.330585e+09,2.397526e+09,2.466543e+09,2.537016e+09,2.610110e+09,2.685746e+09,2.760746e+09,2.842276e+09,...,1.325824e+10,1.537951e+10,1.558511e+10,1.524146e+10,1.803199e+10,1.901725e+10,2.349124e+10,2.703747e+10,0,0
41,Algeria,5.155121e+09,5.363676e+09,7.176428e+09,9.229622e+09,1.325976e+10,1.555555e+10,1.775003e+10,2.099094e+10,2.637376e+10,...,1.898809e+11,1.945545e+11,1.934597e+11,1.648734e+11,1.862317e+11,2.256385e+11,2.476262e+11,2.669723e+11,0,0
58,Andorra,9.947679e+07,1.131285e+08,1.435060e+08,1.908638e+08,2.360555e+08,2.785143e+08,2.875884e+08,3.213901e+08,3.897459e+08,...,3.000160e+09,3.218419e+09,3.155152e+09,2.890998e+09,3.324642e+09,3.380613e+09,3.785063e+09,4.039838e+09,0,0
75,Angola,3.806982e+09,4.007445e+09,4.102155e+09,5.016276e+09,5.626961e+09,4.147433e+09,3.980907e+09,4.344225e+09,4.845482e+09,...,1.398346e+11,1.141892e+11,9.467123e+10,6.652065e+10,8.437511e+10,1.424029e+11,1.143358e+11,1.171594e+11,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3638,Yemen Democratic (Former),1.535912e+08,1.416404e+08,1.585119e+08,1.297606e+08,1.378893e+08,1.404301e+08,1.824448e+08,2.246579e+08,2.710163e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34,34
3655,Yugoslavia (Former),1.455360e+10,1.580174e+10,1.648471e+10,2.147193e+10,2.970621e+10,3.327920e+10,3.756275e+10,4.567289e+10,5.433800e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34,34
3672,Zambia,1.544192e+09,1.574165e+09,1.851647e+09,2.349834e+09,2.894548e+09,2.658265e+09,2.813703e+09,2.767426e+09,3.098138e+09,...,2.587357e+10,2.631149e+10,2.330875e+10,1.813777e+10,2.209642e+10,2.916378e+10,2.757796e+10,2.530319e+10,0,0
3689,Zanzibar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.450834e+09,1.649011e+09,1.807398e+09,1.834626e+09,2.080370e+09,2.344864e+09,2.535120e+09,2.529966e+09,20,10
3706,Zimbabwe,2.336518e+09,2.701725e+09,3.336472e+09,4.103781e+09,4.938099e+09,5.420653e+09,5.357271e+09,5.410607e+09,5.413154e+09,...,3.072024e+10,3.681384e+10,3.929495e+10,3.374722e+10,3.600142e+10,3.896579e+10,4.447631e+10,4.571879e+10,0,0

### Removing Countries with Large Missing in Analysis Period

In [26]:
df_clean = df_gdp[df_gdp["Missing_1980_2024"] <= 3].copy()
df_clean

,Country,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2017,2018,2019,2020,2021,2022,2023,2024,Missing_Count,Missing_1980_2024
7,Afghanistan,1.748887e+09,1.831109e+09,1.595555e+09,1.733333e+09,2.155556e+09,2.366667e+09,2.555556e+09,2.953333e+09,3.300000e+09,...,1.903430e+10,1.885632e+10,1.937236e+10,1.998301e+10,1.516092e+10,1.417499e+10,1.633976e+10,1.828316e+10,0,0
24,Albania,2.265577e+09,2.330585e+09,2.397526e+09,2.466543e+09,2.537016e+09,2.610110e+09,2.685746e+09,2.760746e+09,2.842276e+09,...,1.325824e+10,1.537951e+10,1.558511e+10,1.524146e+10,1.803199e+10,1.901725e+10,2.349124e+10,2.703747e+10,0,0
41,Algeria,5.155121e+09,5.363676e+09,7.176428e+09,9.229622e+09,1.325976e+10,1.555555e+10,1.775003e+10,2.099094e+10,2.637376e+10,...,1.898809e+11,1.945545e+11,1.934597e+11,1.648734e+11,1.862317e+11,2.256385e+11,2.476262e+11,2.669723e+11,0,0
58,Andorra,9.947679e+07,1.131285e+08,1.435060e+08,1.908638e+08,2.360555e+08,2.785143e+08,2.875884e+08,3.213901e+08,3.897459e+08,...,3.000160e+09,3.218419e+09,3.155152e+09,2.890998e+09,3.324642e+09,3.380613e+09,3.785063e+09,4.039838e+09,0,0
75,Angola,3.806982e+09,4.007445e+09,4.102155e+09,5.016276e+09,5.626961e+09,4.147433e+09,3.980907e+09,4.344225e+09,4.845482e+09,...,1.398346e+11,1.141892e+11,9.467123e+10,6.652065e+10,8.437511e+10,1.424029e+11,1.143358e+11,1.171594e+11,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3553,Vanuatu,3.800995e+07,4.106648e+07,5.456834e+07,6.656775e+07,6.638025e+07,8.030427e+07,7.756353e+07,8.125373e+07,9.915994e+07,...,8.800433e+08,9.147279e+08,9.365263e+08,9.094210e+08,9.823622e+08,1.030654e+09,1.090079e+09,1.092148e+09,0,0
3570,Venezuela (Bolivarian Republic of),1.386364e+10,1.522727e+10,1.674419e+10,2.000000e+10,3.046512e+10,3.209302e+10,3.674419e+10,4.232558e+10,4.604651e+10,...,2.470513e+11,2.031269e+11,1.492557e+11,1.058888e+11,1.117747e+11,1.293032e+11,1.394585e+11,1.504938e+11,0,0
3587,Viet Nam,2.775103e+09,3.023992e+09,3.236929e+09,3.350312e+09,3.604731e+09,3.896483e+09,4.540827e+09,5.413318e+09,6.531933e+09,...,2.813536e+11,3.101065e+11,3.343653e+11,3.466157e+11,3.664748e+11,4.134452e+11,4.338577e+11,4.763882e+11,0,0
3672,Zambia,1.544192e+09,1.574165e+09,1.851647e+09,2.349834e+09,2.894548e+09,2.658265e+09,2.813703e+09,2.767426e+09,3.098138e+09,...,2.587357e+10,2.631149e+10,2.330875e+10,1.813777e+10,2.209642e+10,2.916378e+10,2.757796e+10,2.530319e+10,0,0
3706,Zimbabwe,2.336518e+09,2.701725e+09,3.336472e+09,4.103781e+09,4.938099e+09,5.420653e+09,5.357271e+09,5.410607e+09,5.413154e+09,...,3.072024e+10,3.681384e+10,3.929495e+10,3.374722e+10,3.600142e+10,3.896579e+10,4.447631e+10,4.571879e+10,0,0

In [27]:
df_clean.shape # checking count of rows and columns in the cleaned dataframe

(179, 58)

In [28]:
print("Total remaining missing values:",
      df_clean[analysis_years].isna().sum().sum())

Total remaining missing values: 0

In [29]:
df_gdp[analysis_years].isna().sum().sum()

np.int64(622)

### Dropping helper columns

In [30]:
df_clean = df_clean.drop(columns=["Missing_Count", "Missing_1980_2024"])

In [31]:
# Resetting Index
df_clean = df_clean.reset_index(drop=True)
df_clean

,Country,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Afghanistan,1.748887e+09,1.831109e+09,1.595555e+09,1.733333e+09,2.155556e+09,2.366667e+09,2.555556e+09,2.953333e+09,3.300000e+09,...,1.869957e+10,1.822435e+10,1.903430e+10,1.885632e+10,1.937236e+10,1.998301e+10,1.516092e+10,1.417499e+10,1.633976e+10,1.828316e+10
1,Albania,2.265577e+09,2.330585e+09,2.397526e+09,2.466543e+09,2.537016e+09,2.610110e+09,2.685746e+09,2.760746e+09,2.842276e+09,...,1.147017e+10,1.198867e+10,1.325824e+10,1.537951e+10,1.558511e+10,1.524146e+10,1.803199e+10,1.901725e+10,2.349124e+10,2.703747e+10
2,Algeria,5.155121e+09,5.363676e+09,7.176428e+09,9.229622e+09,1.325976e+10,1.555555e+10,1.775003e+10,2.099094e+10,2.637376e+10,...,1.874939e+11,1.807638e+11,1.898809e+11,1.945545e+11,1.934597e+11,1.648734e+11,1.862317e+11,2.256385e+11,2.476262e+11,2.669723e+11
3,Andorra,9.947679e+07,1.131285e+08,1.435060e+08,1.908638e+08,2.360555e+08,2.785143e+08,2.875884e+08,3.213901e+08,3.897459e+08,...,2.789880e+09,2.896613e+09,3.000160e+09,3.218419e+09,3.155152e+09,2.890998e+09,3.324642e+09,3.380613e+09,3.785063e+09,4.039838e+09
4,Angola,3.806982e+09,4.007445e+09,4.102155e+09,5.016276e+09,5.626961e+09,4.147433e+09,3.980907e+09,4.344225e+09,4.845482e+09,...,1.316610e+11,1.147637e+11,1.398346e+11,1.141892e+11,9.467123e+10,6.652065e+10,8.437511e+10,1.424029e+11,1.143358e+11,1.171594e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,Vanuatu,3.800995e+07,4.106648e+07,5.456834e+07,6.656775e+07,6.638025e+07,8.030427e+07,7.756353e+07,8.125373e+07,9.915994e+07,...,7.596902e+08,8.043236e+08,8.800433e+08,9.147279e+08,9.365263e+08,9.094210e+08,9.823622e+08,1.030654e+09,1.090079e+09,1.092148e+09
175,Venezuela (Bolivarian Republic of),1.386364e+10,1.522727e+10,1.674419e+10,2.000000e+10,3.046512e+10,3.209302e+10,3.674419e+10,4.232558e+10,4.604651e+10,...,3.436613e+11,2.878075e+11,2.470513e+11,2.031269e+11,1.492557e+11,1.058888e+11,1.117747e+11,1.293032e+11,1.394585e+11,1.504938e+11
176,Viet Nam,2.775103e+09,3.023992e+09,3.236929e+09,3.350312e+09,3.604731e+09,3.896483e+09,4.540827e+09,5.413318e+09,6.531933e+09,...,2.392583e+11,2.570960e+11,2.813536e+11,3.101065e+11,3.343653e+11,3.466157e+11,3.664748e+11,4.134452e+11,4.338577e+11,4.763882e+11
177,Zambia,1.544192e+09,1.574165e+09,1.851647e+09,2.349834e+09,2.894548e+09,2.658265e+09,2.813703e+09,2.767426e+09,3.098138e+09,...,2.124515e+10,2.096513e+10,2.587357e+10,2.631149e+10,2.330875e+10,1.813777e+10,2.209642e+10,2.916378e+10,2.757796e+10,2.530319e+10
178,Zimbabwe,2.336518e+09,2.701725e+09,3.336472e+09,4.103781e+09,4.938099e+09,5.420653e+09,5.357271e+09,5.410607e+09,5.413154e+09,...,2.229950e+10,2.563996e+10,3.072024e+10,3.681384e+10,3.929495e+10,3.374722e+10,3.600142e+10,3.896579e+10,4.447631e+10,4.571879e+10

In [32]:
# Final Shape of dataset
print("Final Clean Shape:", df_clean.shape)

Final Clean Shape: (179, 56)

## Identifying the Span of years with no missing values.

In [33]:
# Count missing values per year
missing_per_year = df_gdp[year_columns].isna().sum()

missing_per_year.sort_values(ascending=False).describe()

count    55.000000
mean     17.309091
std      11.988996
min       4.000000
25%       8.000000
50%      10.000000
75%      33.000000
max      33.000000
dtype: float64

### Not a single year with no missing values

### Accessing year with missing values less than mean value

In [36]:
complete_years = missing_per_year[missing_per_year < 17].index.tolist()

print("Years with complete data across all countries:")
print(complete_years)

Years with complete data across all countries:
[1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]