# GDP Data Analysis Project

## Project Overview

This notebook presents a structured analysis of Gross Domestic Product (GDP) using a descriptive and analytical workflow. The objective is to clean the source data, construct interpretable growth metrics, and validate key observations with statistical testing.

## Project Phases

### Phase 1: Data Preparation

Prepare the source dataset for analysis by loading the file, reviewing structure, checking data quality, and building a clean GDP-only panel.

### Phase 2: Data Transformation & Analysis

Transform GDP values into a more readable scale, engineer growth-based features, perform hypothesis testing, and develop visual analysis to explain long-term economic patterns.

## Phase 1: Data Preparation

### Import Required Libraries

In [1]:
# =============================================
# Phase 1: Data Preparation - Imports
# =============================================
import pandas as pd
import numpy as np

### Configure Display Options

Set notebook display preferences to improve readability while inspecting intermediate DataFrames.

In [2]:
pd.set_option('display.max_columns', None)
# pd.set_option('display.float_format', '{:.0f}'.format)

### Source File Note

The source workbook had its first two rows removed before analysis because they were not required for the working dataset.

### Load the Dataset

Read the source Excel file and create a working copy for the analysis steps that follow.

In [3]:
# ---------------------------------------------
# Phase 1: Data Preparation - Load source data
# ---------------------------------------------
# Load dataset
file_path = "C:\Projects\DAP\gdp-growth-analysis\data\GDPcurrent-USD-countries.xlsx"
df_original = pd.read_excel(file_path)

# Create working copy
df = df_original.copy()

df.head(15)

,CountryID,Country,IndicatorName,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,4,Afghanistan,Final consumption expenditure,1.691109e+09,1.826664e+09,1.544444e+09,1.637778e+09,1.984444e+09,2.173333e+09,2.248889e+09,2.680000e+09,2.942222e+09,3.302300e+09,3.267891e+09,3.109967e+09,3.077043e+09,3.043752e+09,3.006623e+09,2.972943e+09,2.971971e+09,2.583997e+09,2.384419e+09,2.991105e+09,3.241082e+09,3.116502e+09,3.374469e+09,2.689199e+09,2.214902e+09,3.513194e+09,3.510794e+09,3.504356e+09,3.494164e+09,3.367516e+09,4.507324e+09,4.646550e+09,5.092313e+09,6.318556e+09,6.630614e+09,7.348229e+09,7.717236e+09,1.061808e+10,1.003314e+10,1.144096e+10,1.555934e+10,1.950281e+10,2.282465e+10,2.190741e+10,2.016074e+10,1.905434e+10,1.841552e+10,1.859587e+10,2.082703e+10,2.138090e+10,2.286309e+10,1.663770e+10,1.693301e+10,2.009309e+10,2.708702e+10
1,4,Afghanistan,Household consumption expenditure (including N...,1.577102e+09,1.703519e+09,1.440325e+09,1.527366e+09,1.850662e+09,2.026817e+09,2.097279e+09,2.499326e+09,2.743871e+09,3.079673e+09,3.047584e+09,2.900307e+09,2.869603e+09,2.838556e+09,2.803929e+09,2.772521e+09,2.771613e+09,2.409795e+09,2.223676e+09,2.789451e+09,3.022580e+09,2.906426e+09,3.146933e+09,2.507913e+09,2.065659e+09,3.276081e+09,3.274290e+09,3.268555e+09,3.257178e+09,3.141952e+09,4.205070e+09,4.323944e+09,4.764065e+09,5.873886e+09,6.076023e+09,6.679164e+09,6.895654e+09,9.476716e+09,8.965251e+09,9.850898e+09,1.284197e+10,1.615808e+10,1.851736e+10,1.758409e+10,1.581518e+10,1.496906e+10,1.429584e+10,1.460787e+10,1.688326e+10,1.721976e+10,1.844500e+10,1.341413e+10,1.383642e+10,1.662669e+10,2.212882e+10
2,4,Afghanistan,General government final consumption expenditure,1.140071e+08,1.231456e+08,1.041196e+08,1.104117e+08,1.337824e+08,1.465165e+08,1.516101e+08,1.806737e+08,1.983516e+08,2.226263e+08,2.203067e+08,2.096603e+08,2.074404e+08,2.051963e+08,2.026935e+08,2.004216e+08,2.003579e+08,1.742027e+08,1.607430e+08,2.016531e+08,2.185021e+08,2.100762e+08,2.275363e+08,1.812863e+08,1.492436e+08,2.371125e+08,2.365033e+08,2.358013e+08,2.369860e+08,2.255644e+08,3.022539e+08,3.226067e+08,3.282483e+08,4.446709e+08,5.545905e+08,6.690649e+08,8.215816e+08,1.141359e+09,1.067892e+09,1.590066e+09,2.717373e+09,3.344724e+09,4.307286e+09,4.323323e+09,4.345557e+09,4.085273e+09,4.119686e+09,3.987993e+09,3.943771e+09,4.161138e+09,4.418088e+09,3.223572e+09,3.096592e+09,3.466403e+09,4.958199e+09
3,4,Afghanistan,Gross capital formation,9.555556e+07,9.999998e+07,1.044445e+08,1.266666e+08,1.888889e+08,2.311111e+08,3.488889e+08,3.666667e+08,4.577778e+08,4.923139e+08,4.807147e+08,4.683080e+08,4.582337e+08,4.531121e+08,4.493578e+08,4.432086e+08,4.432228e+08,3.855935e+08,3.556271e+08,4.461773e+08,4.835024e+08,4.421070e+08,4.559426e+08,3.465847e+08,2.726524e+08,4.135871e+08,3.957141e+08,3.785828e+08,3.621631e+08,3.351823e+08,4.311966e+08,4.922650e+08,4.839938e+08,5.348199e+08,8.632883e+08,1.191371e+09,1.434622e+09,1.487765e+09,1.285069e+09,1.530317e+09,1.989911e+09,2.372607e+09,3.013381e+09,2.985915e+09,2.795861e+09,2.711463e+09,2.331712e+09,2.640511e+09,2.689519e+09,2.434404e+09,2.289180e+09,1.968903e+09,2.362752e+09,2.490757e+09,2.041052e+09
4,4,Afghanistan,Gross fixed capital formation (including Acqui...,9.555556e+07,9.999998e+07,1.044445e+08,1.266666e+08,1.888889e+08,2.311111e+08,3.488889e+08,3.666667e+08,4.577778e+08,4.923139e+08,4.807147e+08,4.683080e+08,4.582337e+08,4.531121e+08,4.493578e+08,4.432086e+08,4.432228e+08,3.855935e+08,3.556271e+08,4.461773e+08,4.835024e+08,4.421070e+08,4.559426e+08,3.465847e+08,2.726524e+08,4.135871e+08,3.957141e+08,3.785828e+08,3.621631e+08,3.351823e+08,4.311966e+08,4.922650e+08,4.839938e+08,5.348199e+08,8.632883e+08,1.191371e+09,1.434622e+09,1.487765e+09,1.285069e+09,1.530317e+09,1.989911e+09,2.372607e+09,3.013381e+09,2.985915e+09,2.795861e+09,2.711463e+09,2.331712e+09,2.640511e+09,2.689519e+09,2.434404e+09,2.289180e+09,1.968903e+09,2.362752e+09,2.490757e+09,2.041052e+09
5,4,Afghanistan,Exports of goods and services,1.711111e+08,2.000000e+08,2.355555e+08,2.244444e+08,3.022222e+08,3.000000e+08,3.377778e+08,3.444445e+08,3.577778e+08,4.403267e+08,4.177300e+08,3.968110e+08,3.987341e+08,3.906196e+08,3.863635e+08,3.829372e+08,3.820434e+08,3.323541e+08,3.067764e+08,3.846837e+08,4.168984e+08,4.618978e+08,5.610187e+08,4.919469e+08,4.394376e+08,7.475381e+08,7.940860e+08,8.365194e+08,8.750673e+08,8.804131e+08,1.225052e+09,1.221289e+09,1.270931e+09,2.033321e+09,1.806326e+09,1.878038e+09,2.108934e+09,2.121890e+09,2.136954e+09,2.406835e+09,2.343235e+09,2.015378e+09,2.503510e+09,3.029989e+09,3.093255e+09,3.270651e+09,3.324497e+09,4.178086e+09,2.944149e+09,2.376329e+09,2.082394e+09,2.174408e+09,2.605367e+09,2.652801e+09,1.822967e+09
6,4,Afghanistan,Imports of goods and services,2.088889e+08,2.955556e+08,2.888889e+08,2.555556e+08,3.200000e+08,3.377778e+08,3.800000e+08,4.377778e+08,4.577778e+08,5.370000e+08,5.246124e+08,4.962985e+08,4.951263e+08,4.880450e+08,4.818984e+08,4.771890e+08,4.766377e+08,4.144449e+08,3.825222e+08,4.797657e+08,5.198829e+08,6.804062e+08,9.168291e+08,8.633291e+08,8.123903e+08,1.438015e+09,1.576230e+09,1.703163e+09,1.819429e+09,1.863114e+09,2.631695e+09,2.739569e+09,2.562046e+09,3.987906e+09,3.796155e+09,3.942657e+09,3.967899e+09,4.228394e+09,3.159020e+09,3.446516e+09,4.747914e+09,5.967689e+09,8.547131e+09,8.018906e+09,6.549392e+09,6.336878e+09,5.886743e+09,6.432581e+09,7.733530e+09,6.819277e+09,7.251652e+09,5.620091e+09,7.726136e+09,8.294765e+09,1.266788e+10
7,4,Afghanistan,Gross Domestic Product (GDP),1.748887e+09,1.831109e+09,1.595555e+09,1.733333e+09,2.155556e+09,2.366667e+09,2.555556e+09,2.953333e+09,3.300000e+09,3.697940e+09,3.641723e+09,3.478788e+09,3.438885e+09,3.399439e+09,3.360446e+09,3.321900e+09,3.320600e+09,2.887500e+09,2.664300e+09,3.342200e+09,3.621600e+09,3.340100e+09,3.474600e+09,2.664400e+09,2.114600e+09,3.236300e+09,3.124359e+09,3.016291e+09,2.911960e+09,2.719992e+09,3.531869e+09,3.620525e+09,4.285191e+09,4.898791e+09,5.504073e+09,6.474980e+09,7.292893e+09,9.999336e+09,1.029615e+10,1.193160e+10,1.514457e+10,1.792310e+10,1.979441e+10,1.990441e+10,1.950046e+10,1.869957e+10,1.822435e+10,1.903430e+10,1.885632e+10,1.937236e+10,1.998301e+10,1.516092e+10,1.417499e+10,1.633976e+10,1.828316e+10
8,4,Afghanistan,"Agriculture, hunting, forestry, fishing (ISIC ...",8.786878e+08,9.200109e+08,8.016412e+08,8.708712e+08,1.083068e+09,1.188976e+09,1.284010e+09,1.484166e+09,1.657179e+09,1.858590e+09,1.831206e+09,1.743166e+09,1.732785e+09,1.711813e+09,1.666160e+09,1.701700e+09,1.668900e+09,1.364600e+09,1.632400e+09,2.262900e+09,1.294400e+09,1.660000e+09,1.926500e+09,1.691400e+09,1.549800e+09,2.125800e+09,1.994876e+09,1.872016e+09,1.756722e+09,1.595022e+09,2.013192e+09,1.927812e+09,1.849756e+09,2.027964e+09,1.862387e+09,2.272586e+09,2.462249e+09,3.504386e+09,3.003034e+09,3.934798e+09,4.493103e+09,5.211051e+09,5.462841e+09,5.382080e+09,5.188963e+09,4.532803e+09,4.719622e+09,4.839053e+09,4.325516e+09,5.028423e+09,5.990027e+09,5.093709e+09,4.777172e+09,5.676968e+09,6.218851e+09
9,4,Afghanistan,"Mining, Manufacturing, Utilities (ISIC C-E)",3.804876e+08,3.983764e+08,3.471234e+08,3.771092e+08,4.689650e+08,5.148572e+08,5.560447e+08,6.425133e+08,7.177429e+08,8.050230e+08,7.919769e+08,7.560293e+08,7.506613e+08,7.370239e+08,7.288226e+08,7.347000e+08,7.052000e+08,6.269000e+08,4.556000e+08,5.202000e+08,7.457000e+08,6.772000e+08,4.206000e+08,2.786000e+08,1.734000e+08,1.758000e+08,2.136448e+08,2.596365e+08,3.155289e+08,3.710074e+08,6.064300e+08,7.135947e+08,7.336183e+08,7.222998e+08,8.049299e+08,8.499023e+08,8.835742e+08,1.244362e+09,1.229097e+09,1.042375e+09,1.235461e+09,1.614133e+09,1.544971e+09,1.375614e+09,1.322779e+09,1.283435e+09,1.298744e+09,1.438979e+09,1.898473e+09,2.672112e+09,2.192681e+09,1.953132e+09,2.132734e+09,2.062692e+09,2.471407e+09
10,4,Afghanistan,Manufacturing (ISIC D),3.738776e+08,3.914557e+08,3.410931e+08,3.705580e+08,4.608180e+08,5.059129e+08,5.463849e+08,6.313514e+08,7.052739e+08,7.910381e+08,7.782183e+08,7.428948e+08,7.376218e+08,7.242193e+08,7.161592e+08,7.219428e+08,6.929423e+08,6.160045e+08,4.476928e+08,5.111808e+08,7.327521e+08,6.653679e+08,4.132939e+08,2.737986e+08,1.704089e+08,1.727252e+08,2.097958e+08,2.552580e+08,3.103064e+08,3.645791e+08,5.950927e+08,6.988652e+08,7.254724e+08,7.090186e+08,7.805849e+08,8.123673e+08,8.287087e+08,1.154475e+09,1.129829e+09,9.114989e+08,1.030385e+09,1.217475e+09,1.151919e+09,9.785696e+08,9.063296e+08,8.093483e+08,7.252140e+08,7.860463e+08,1.201587e+09,1.949719e+09,1.504342e+09,1.287645e+09,1.444470e+09,1.232165e+09,1.598213e+09
11,4,Afghanistan,Construction (ISIC F),4.726559e+07,4.948797e+07,4.312017e+07,4.684664e+07,5.825735e+07,6.395215e+07,6.908195e+07,7.981590e+07,8.912752e+07,1.000743e+08,9.835053e+07,9.377502e+07,9.361920e+07,9.124031e+07,9.007738e+07,9.309999e+07,8.529999e+07,7.710001e+07,6.370000e+07,7.930001e+07,1.125000e+08,1.064000e+08,1.349000e+08,1.039000e+08,7.650000e+07,1.646000e+08,1.644798e+08,1.643597e+08,1.642397e+08,1.587929e+08,2.134217e+08,2.295673e+08,1.840763e+08,2.312109e+08,3.673287e+08,4.758378e+08,5.676964e+08,5.507873e+08,5.316759e+08,5.584607e+08,6.420562e+08,6.657690e+08,7.016191e+08,6.865166e+08,7.003461e+08,6.984710e+08,5.912986e+08,6.189839e+08,6.562628e+08,4.467343e+08,3.956404e+08,2.108892e+08,1.424053e+08,1.349722e+08,1.963406e+08
12,4,Afghanistan,"Wholesale, retail trade, restaurants and hotel...",2.286665e+08,2.394057e+08,2.086407e+08,2.266196e+08,2.817847e+08,3.096171e+08,3.339529e+08,3.859217e+08,4.327023e+08,4.816067e+08,4.758326e+08,4.608275e+08,4.387336e+08,4.485088e+08,4.633623e+08,3.751000e+08,4.815000e+08,4.497000e+08,2.430000e+08,1.548000e+08,1.007300e+09,4.563000e+08,4.819000e+08,3.265000e+08,1.377000e+08,3.121000e+08,2.551620e+08,2.086115e+08,1.705534e+08,1.349126e+08,1.483541e+08,1.673352e+08,4.305694e+08,4.738887e+08,5.360471e+08,6.150786e+08,6.908348e+08,9.854494e+08,1.070532e+09,1.127913e+09,1.491504e+09,1.812688e+09,2.255267e+09,2.242103e+09,2.172342e+09,2.233704e+09,2.039871e+09,2.248199e+09,2.147227e+09,1.806462e+09,1.642015e+09,1.278561e+09,1.153074e+09,1.782716e+09,1.674623e+09
13,4,Afghanistan,"Transport, storage and communication (ISIC I)",8.476256e+07,8.874546e+07,7.732715e+07,8.401507e+07,1.044624e+08,1.146889e+08,1.239155e+08,1.430508e+08,1.599002e+08,1.796249e+08,1.758306e+08,1.687464e+08,1.682766e+08,1.611538e+08,1.652742e+08,1.668000e+08,1.422000e+08,1.574000e+08,1.221000e+08,1.519000e+08,2.203000e+08,2.128000e+08,2.530000e+08,8.660000e+07,5.730000e+07,2.125000e+08,2.151339e+08,2.178004e+08,2.205000e+08,2.159875e+08,2.941056e+08,3.443510e+08,4.289613e+08,5.871359e+08,6.661398e+08,6.011669e+08,6.888584e+08,9.623460e+08,1.122795e+09,1.315692e+09,1.649004e+09,1.807137e+09,2.128753e+09,2.186522e+09,1.914311e+09,1.769949e+09,1.582007e+09,1.601224e+09,1.605562e+09,1.816073e+09,2.017421e+09,1.324995e+09,1.245113e+09,1.271169e+09,1.542063e+09
14,4,Afghanistan,Other Activities (ISIC J-P),1.290355e+08,1.351023e+08,1.177200e+08,1.278903e+08,1.590416e+08,1.746003e+08,1.885786e+08,2.178975e+08,2.433831e+08,2.730642e+08,2.685622e+08,2.562795e+08,2.548612e+08,2.497125e+08,2.467879e+08,2.506000e+08,2.374000e+08,2.119000e+08,1.474000e+08,1.730000e+08,2.414000e+08,2.274000e+08,2.577000e+08,1.774000e+08,1.199000e+08,2.455000e+08,2.349090e+08,2.247840e+08,2.151040e+08,1.991677e+08,2.563663e+08,2.378649e+08,6.038127e+08,7.183912e+08,1.078010e+09,1.439518e+09,1.715697e+09,2.329821e+09,2.880095e+09,3.694486e+09,5.717982e+09,7.183140e+09,7.835848e+09,8.590673e+09,9.826969e+09,1.006235e+10,7.105497e+09,7.302901e+09,7.281032e+09,6.714968e+09,6.846058e+09,4.546402e+09,3.987633e+09,4.523575e+09,5.229200e+09

## Phase 2: Data Transformation & Analysis

### Convert GDP Values to Billions

The raw numeric values are converted from current US dollars to billions of current US dollars. This improves readability, simplifies comparison across countries and years, and makes the subsequent descriptive analysis and visualization easier to interpret.

In [4]:
# ---------------------------------------------
# Phase 2: Data Transformation - Scale GDP to billions
# ---------------------------------------------
# Step 1: Identify year columns
years = [col for col in df.columns if str(col).isdigit()]

# Step 2: Convert to numeric (IMPORTANT)
df[years] = df[years].apply(pd.to_numeric, errors='coerce')

# Step 3: Convert to billions
df[years] = (df[years] / 1e9).round(3)

df.head()

,CountryID,Country,IndicatorName,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,4,Afghanistan,Final consumption expenditure,1.691,1.827,1.544,1.638,1.984,2.173,2.249,2.680,2.942,3.302,3.268,3.110,3.077,3.044,3.007,2.973,2.972,2.584,2.384,2.991,3.241,3.117,3.374,2.689,2.215,3.513,3.511,3.504,3.494,3.368,4.507,4.647,5.092,6.319,6.631,7.348,7.717,10.618,10.033,11.441,15.559,19.503,22.825,21.907,20.161,19.054,18.416,18.596,20.827,21.381,22.863,16.638,16.933,20.093,27.087
1,4,Afghanistan,Household consumption expenditure (including N...,1.577,1.704,1.440,1.527,1.851,2.027,2.097,2.499,2.744,3.080,3.048,2.900,2.870,2.839,2.804,2.773,2.772,2.410,2.224,2.789,3.023,2.906,3.147,2.508,2.066,3.276,3.274,3.269,3.257,3.142,4.205,4.324,4.764,5.874,6.076,6.679,6.896,9.477,8.965,9.851,12.842,16.158,18.517,17.584,15.815,14.969,14.296,14.608,16.883,17.220,18.445,13.414,13.836,16.627,22.129
2,4,Afghanistan,General government final consumption expenditure,0.114,0.123,0.104,0.110,0.134,0.147,0.152,0.181,0.198,0.223,0.220,0.210,0.207,0.205,0.203,0.200,0.200,0.174,0.161,0.202,0.219,0.210,0.228,0.181,0.149,0.237,0.237,0.236,0.237,0.226,0.302,0.323,0.328,0.445,0.555,0.669,0.822,1.141,1.068,1.590,2.717,3.345,4.307,4.323,4.346,4.085,4.120,3.988,3.944,4.161,4.418,3.224,3.097,3.466,4.958
3,4,Afghanistan,Gross capital formation,0.096,0.100,0.104,0.127,0.189,0.231,0.349,0.367,0.458,0.492,0.481,0.468,0.458,0.453,0.449,0.443,0.443,0.386,0.356,0.446,0.484,0.442,0.456,0.347,0.273,0.414,0.396,0.379,0.362,0.335,0.431,0.492,0.484,0.535,0.863,1.191,1.435,1.488,1.285,1.530,1.990,2.373,3.013,2.986,2.796,2.711,2.332,2.641,2.690,2.434,2.289,1.969,2.363,2.491,2.041
4,4,Afghanistan,Gross fixed capital formation (including Acqui...,0.096,0.100,0.104,0.127,0.189,0.231,0.349,0.367,0.458,0.492,0.481,0.468,0.458,0.453,0.449,0.443,0.443,0.386,0.356,0.446,0.484,0.442,0.456,0.347,0.273,0.414,0.396,0.379,0.362,0.335,0.431,0.492,0.484,0.535,0.863,1.191,1.435,1.488,1.285,1.530,1.990,2.373,3.013,2.986,2.796,2.711,2.332,2.641,2.690,2.434,2.289,1.969,2.363,2.491,2.041

### Inspect Dataset Structure

Review dataset size, column layout, data types, and missing values before filtering the analysis scope.

In [5]:
# ---------------------------------------------
# Inspect overall dataset structure and quality
# ---------------------------------------------
print("Shape of dataset:", df.shape) ## to check the shape of the dataset

print("\nColumn Names:")
print(df.columns.tolist()) ## gives the name of the columns in list format

print("\nDataset Info:")
df.info() 

print("\nMissing Values per Column:")
print(df.isnull().sum()) ## to calculate the sum of null values in each column present in the dataset

Shape of dataset: (3715, 58)

Column Names:
['CountryID', 'Country', 'IndicatorName', 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3715 entries, 0 to 3714
Data columns (total 58 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryID      3715 non-null   int64
 1   Country        3715 non-null   object
 2   IndicatorName  3715 non-null   object
 3   1970           3122 non-null   float64
 4   1971           3122 non-null   float64
 5   1972           3123 non-null   float64
 6   1973           3125 non-null   float64
 7   1974           3123 non-null   float64
 8   1975           3125 non-null   float64
 9   1976           3124 non-null   float64
 10  1977           3124 non-null   float64
 11  1978           3124 non-null   float64
 12  1979           3127 non-null   float64
 13  1980           3128 non-null   float64
 14  1981           3129 non-null   float64
 15  1982           3130 non-null   float64
 16  1983           3130 non-null   float64
 17  1984           3131 non-null   float64
 18  1985           3133 non-null   float64
 19  1986           3132 non-null   float64
 20  1987           3136 non-null   float64
 21  1988           3136 non-null   float64
 22  1989           3152 non-null   float64
 23  1990           3624 non-null   float64
 24  1991           3543 non-null   float64
 25  1992           3538 non-null   float64
 26  1993           3541 non-null   float64
 27  1994           3525 non-null   float64
 28  1995           3526 non-null   float64
 29  1996           3526 non-null   float64
 30  1997           3527 non-null   float64
 31  1998           3523 non-null   float64
 32  1999           3523 non-null   float64
 33  2000           3525 non-null   float64
 34  2001           3527 non-null   float64
 35  2002           3530 non-null   float64
 36  2003           3529 non-null   float64
 37  2004           3534 non-null   float64
 38  2005           3565 non-null   float64
 39  2006           3567 non-null   float64
 40  2007           3566 non-null   float64
 41  2008           3599 non-null   float64
 42  2009           3597 non-null   float64
 43  2010           3596 non-null   float64
 44  2011           3580 non-null   float64
 45  2012           3579 non-null   float64
 46  2013           3561 non-null   float64
 47  2014           3560 non-null   float64
 48  2015           3561 non-null   float64
 49  2016           3561 non-null   float64
 50  2017           3560 non-null   float64
 51  2018           3560 non-null   float64
 52  2019           3561 non-null   float64
 53  2020           3560 non-null   float64
 54  2021           3558 non-null   float64
 55  2022           3557 non-null   float64
 56  2023           3556 non-null   float64
 57  2024           3550 non-null   float64
dtypes: float64(55), int64(1), object(2)
memory usage: 1.6+ MB

Missing Values per Column:
CountryID          0
Country            0
IndicatorName      0
1970             593
1971             593
1972             592
1973             590
1974             592
1975             590
1976             591
1977             591
1978             591
1979             588
1980             587
1981             586
1982             585
1983             585
1984             584
1985             582
1986             583
1987             579
1988             579
1989             563
1990              91
1991             172
1992             177
1993             174
1994             190
1995             189
1996             189
1997             188
1998             192
1999             192
2000             190
2001             188
2002             185
2003             186
2004             181
2005             150
2006             148
2007             149
2008             116
2009             118
2010             119
2011             135
2012             136
2013             154
2014             155
2015             154
2016             154
2017             155
2018             155
2019             154
2020             155
2021             157
2022             158
2023             159
2024             165
dtype: int64

### Review Column Data Types

In [6]:
df.dtypes

CountryID          int64
Country           object
IndicatorName     object
1970             float64
1971             float64
1972             float64
1973             float64
1974             float64
1975             float64
1976             float64
1977             float64
1978             float64
1979             float64
1980             float64
1981             float64
1982             float64
1983             float64
1984             float64
1985             float64
1986             float64
1987             float64
1988             float64
1989             float64
1990             float64
1991             float64
1992             float64
1993             float64
1994             float64
1995             float64
1996             float64
1997             float64
1998             float64
1999             float64
2000             float64
2001             float64
2002             float64
2003             float64
2004             float64
2005             float64
2006             float64
2007             float64
2008             float64
2009             float64
2010             float64
2011             float64
2012             float64
2013             float64
2014             float64
2015             float64
2016             float64
2017             float64
2018             float64
2019             float64
2020             float64
2021             float64
2022             float64
2023             float64
2024             float64
dtype: object

### Check for Duplicate Rows

In [7]:
df.duplicated().sum()

np.int64(0)

No duplicate rows are present in the dataset. If duplicates were found, they could be handled with `df.drop_duplicates()`.

### Generate Descriptive Summary Statistics

In [8]:
df.describe()

,CountryID,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
count,3715.000000,3122.000000,3122.000000,3123.000000,3125.000000,3123.000000,3125.000000,3124.000000,3124.000000,3124.000000,3127.000000,3128.000000,3129.000000,3130.000000,3130.000000,3131.000000,3133.000000,3132.000000,3136.000000,3136.000000,3152.000000,3624.000000,3543.000000,3538.000000,3541.000000,3525.000000,3526.000000,3526.000000,3527.000000,3523.000000,3523.000000,3525.000000,3527.000000,3530.000000,3529.000000,3534.000000,3565.000000,3567.000000,3566.000000,3599.000000,3597.000000,3596.000000,3580.000000,3579.000000,3561.000000,3560.000000,3561.000000,3561.000000,3560.000000,3560.000000,3561.000000,3560.000000,3558.000000,3557.000000,3556.000000,3550.000000
mean,439.346972,5.922917,6.516354,7.501359,9.171421,10.498658,11.689975,12.680815,14.296394,16.913975,19.502352,21.891585,22.324655,22.060849,22.528312,23.211701,23.750451,27.271438,30.858926,34.598067,35.943353,36.168892,37.268947,39.927984,40.412818,43.372805,48.205230,49.236846,49.134096,48.890993,50.827412,52.666593,52.235404,54.237567,61.022993,69.112658,74.554314,81.101263,91.744634,100.500071,93.959457,103.604160,116.387709,118.890131,122.947484,126.232891,118.978151,120.359151,128.497562,136.931876,138.543008,134.172883,154.404288,162.191931,168.326708,175.057630
std,253.959998,40.017374,43.425234,48.678956,55.969263,60.643763,66.734873,72.949479,81.726182,95.173834,106.448602,116.618809,125.024403,128.605627,137.819433,149.381211,159.358254,177.264463,195.318765,216.320936,226.503878,227.167399,241.264004,258.312291,272.660715,293.095740,316.304723,318.426815,323.852215,333.176797,355.772118,376.639878,380.403782,391.780626,418.200289,450.924720,476.344389,502.593240,535.346134,560.319973,550.430466,583.323862,628.318340,653.331661,676.768626,706.802849,718.182956,737.541305,777.642730,832.748583,859.285317,857.818082,978.251039,1036.143141,1084.166140,1134.447346
min,4.000000,-0.398000,-1.322000,-2.076000,-4.093000,-0.646000,-6.256000,-1.041000,-1.084000,-6.342000,-5.509000,-8.172000,-7.576000,-14.914000,-8.605000,-10.583000,-6.561000,-5.708000,-5.821000,-6.895000,-3.835000,-12.734000,-12.663000,-9.628000,-16.171000,-17.156000,-23.033000,-11.682000,-12.002000,-7.941000,-32.527000,-3.463000,-38.284000,-15.123000,-7.364000,-3.135000,-6.485000,-3.472000,-6.993000,-29.242000,-150.772000,-4.713000,-4.312000,-27.321000,-8.401000,-7.203000,-21.062000,-38.509000,-21.641000,-67.765000,-8.368000,-30.400000,-4.732000,-3.228000,-21.163000,-72.181000
25%,214.000000,0.030000,0.033250,0.039000,0.049000,0.061000,0.066000,0.070750,0.082000,0.093000,0.109000,0.126000,0.120000,0.122250,0.118000,0.130500,0.127000,0.138000,0.155750,0.173750,0.182750,0.215750,0.220500,0.228000,0.225000,0.232000,0.254250,0.270000,0.277000,0.289000,0.278000,0.289000,0.303500,0.325000,0.373000,0.429250,0.471000,0.536000,0.645500,0.739000,0.668000,0.780500,0.875000,0.864000,0.925000,0.961750,0.876000,0.871000,0.958000,1.048500,1.034000,0.943250,1.113250,1.227000,1.218750,1.328250
50%,440.000000,0.220000,0.240500,0.276000,0.344000,0.443000,0.486000,0.536000,0.604500,0.689000,0.800000,0.885000,0.899000,0.898000,0.878500,0.908000,0.905000,0.994500,1.043500,1.153500,1.184500,1.388000,1.289000,1.302000,1.266000,1.292000,1.453500,1.518500,1.575000,1.651000,1.613000,1.648000,1.717000,1.791000,2.046000,2.370000,2.658000,3.111000,3.715000,4.538000,4.098000,4.549500,5.147000,5.447000,5.844000,6.042000,5.491000,5.567000,5.936000,6.349000,6.355000,5.908500,6.894500,7.427000,7.711500,8.131500
75%,661.000000,1.472000,1.606500,1.848000,2.355000,3.037000,3.226000,3.653500,4.191000,4.694250,5.425500,6.335750,6.445000,6.485000,6.441000,6.605500,6.421000,6.799250,7.437000,8.244750,8.595750,8.261250,7.765000,8.181750,8.230000,8.688000,9.603500,9.891250,10.318500,10.248500,10.295000,10.530000,10.881000,11.391250,13.142000,15.291750,17.146000,20.225500,24.701000,29.131500,26.950000,30.432500,34.743750,35.029000,37.664000,38.314750,35.370000,34.824000,37.232250,40.436500,40.578000,38.692750,43.637500,46.516000,48.404250,50.702750
max,894.000000,1073.303000,1164.850000,1279.110000,1425.376000,1545.243000,1684.904000,1873.412000,2081.826000,2351.599000,2627.333000,2857.307000,3207.041000,3352.534000,3634.038000,4037.613000,4338.979000,4579.631000,4891.807000,5314.835000,5645.048000,5963.144000,6171.961000,6520.327000,6858.559000,7287.236000,7639.749000,8073.122000,8577.600000,9062.817000,9631.400000,10250.952000,10582.000000,10929.108000,11456.450000,12217.196000,13039.400000,13815.700000,14474.228000,14769.862000,14478.100000,15048.971000,15599.732000,16254.000000,16880.804000,17608.138000,18295.019000,18804.913000,19612.104000,20656.518000,21540.000000,21375.300000,23725.600000,26054.600000,27811.500000,29298.000000

### Review Available Indicators

In [9]:
print("Unique Indicators:")
print(df["IndicatorName"].unique())
print("Number of Indicators: ", len(df["IndicatorName"].unique()))

Unique Indicators:
['Final consumption expenditure'
 'Household consumption expenditure (including Non-profit institutions serving households)'
 'General government final consumption expenditure'
 'Gross capital formation'
 'Gross fixed capital formation (including Acquisitions less disposals of valuables)'
 'Exports of goods and services' 'Imports of goods and services'
 'Gross Domestic Product (GDP)'
 'Agriculture, hunting, forestry, fishing (ISIC A-B)'
 'Mining, Manufacturing, Utilities (ISIC C-E)' 'Manufacturing (ISIC D)'
 'Construction (ISIC F)'
 'Wholesale, retail trade, restaurants and hotels (ISIC G-H)'
 'Transport, storage and communication (ISIC I)'
 'Other Activities (ISIC J-P)' 'Total Value Added'
 'Changes in inventories']
Number of Indicators:  17

### Filter the Dataset to GDP Records

Create a dedicated GDP-only DataFrame to support focused country-level analysis.

In [10]:
# ---------------------------------------------
# Build a GDP-only working dataset
# ---------------------------------------------
df_gdp = df[df["IndicatorName"].str.contains("GDP", case=False)]

df_gdp.head()

,CountryID,Country,IndicatorName,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
7,4,Afghanistan,Gross Domestic Product (GDP),1.749,1.831,1.596,1.733,2.156,2.367,2.556,2.953,3.300,3.698,3.642,3.479,3.439,3.399,3.360,3.322,3.321,2.887,2.664,3.342,3.622,3.340,3.475,2.664,2.115,3.236,3.124,3.016,2.912,2.720,3.532,3.621,4.285,4.899,5.504,6.475,7.293,9.999,10.296,11.932,15.145,17.923,19.794,19.904,19.500,18.700,18.224,19.034,18.856,19.372,19.983,15.161,14.175,16.340,18.283
24,8,Albania,Gross Domestic Product (GDP),2.266,2.331,2.398,2.467,2.537,2.610,2.686,2.761,2.842,2.372,2.142,2.215,2.280,2.305,2.276,2.324,2.397,2.378,2.460,2.941,2.146,1.597,1.516,1.700,1.881,2.905,3.234,2.259,2.609,3.294,3.592,4.064,4.523,5.750,7.399,8.257,9.151,11.117,13.259,12.336,12.087,12.974,12.247,12.797,13.296,11.470,11.989,13.258,15.380,15.585,15.241,18.032,19.017,23.491,27.037
41,12,Algeria,Gross Domestic Product (GDP),5.155,5.364,7.176,9.230,13.260,15.556,17.750,20.991,26.374,33.201,42.252,44.265,45.095,48.702,52.828,57.866,62.923,64.334,58.655,55.344,61.751,46.565,49.106,50.847,42.331,41.971,46.836,48.806,49.566,50.800,58.101,59.413,61.516,73.482,91.914,107.047,123.084,142.483,180.384,150.317,177.785,218.332,227.144,229.701,238.943,187.494,180.764,189.881,194.554,193.460,164.873,186.232,225.638,247.626,266.972
58,20,Andorra,Gross Domestic Product (GDP),0.099,0.113,0.144,0.191,0.236,0.279,0.288,0.321,0.390,0.521,0.565,0.492,0.476,0.415,0.418,0.439,0.610,0.773,0.913,1.007,1.302,1.401,1.531,1.274,1.288,1.491,1.549,1.494,1.534,1.569,1.433,1.548,1.764,2.367,2.900,3.161,3.459,3.958,4.102,3.689,3.450,3.629,3.189,3.194,3.272,2.790,2.897,3.000,3.218,3.155,2.891,3.325,3.381,3.785,4.040
75,24,Angola,Gross Domestic Product (GDP),3.807,4.007,4.102,5.016,5.627,4.147,3.981,4.344,4.845,5.380,7.151,6.693,6.693,6.975,7.394,9.109,8.549,9.844,10.716,12.574,14.006,16.734,19.374,14.156,14.690,7.098,9.402,11.112,9.441,9.089,13.598,13.420,17.312,20.342,26.998,41.397,58.654,73.038,98.790,81.705,95.547,125.552,143.573,153.761,164.448,131.661,114.764,139.835,114.189,94.671,66.521,84.375,142.403,114.336,117.159

### Inspect the GDP-Only Dataset

In [11]:
print("Shape after GDP filter:", df_gdp.shape)
print("Informations about data in df_gdp: \n", df_gdp.info())

Shape after GDP filter: (220, 58)
<class 'pandas.core.frame.DataFrame'>
Index: 220 entries, 7 to 3706
Data columns (total 58 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryID      220 non-null    int64
 1   Country        220 non-null    object
 2   IndicatorName  220 non-null    object
 3   1970           187 non-null    float64
 4   1971           187 non-null    float64
 5   1972           187 non-null    float64
 6   1973           187 non-null    float64
 7   1974           187 non-null    float64
 8   1975           187 non-null    float64
 9   1976           187 non-null    float64
 10  1977           187 non-null    float64
 11  1978           187 non-null    float64
 12  1979           187 non-null    float64
 13  1980           187 non-null    float64
 14  1981           187 non-null    float64
 15  1982           187 non-null    float64
 16  1983           187 non-null    float64
 17  1984           187 non-null    float64
 18  1985           187 non-null    float64
 19  1986           187 non-null    float64
 20  1987           187 non-null    float64
 21  1988           187 non-null    float64
 22  1989           188 non-null    float64
 23  1990           216 non-null    float64
 24  1991           211 non-null    float64
 25  1992           211 non-null    float64
 26  1993           211 non-null    float64
 27  1994           210 non-null    float64
 28  1995           210 non-null    float64
 29  1996           210 non-null    float64
 30  1997           210 non-null    float64
 31  1998           210 non-null    float64
 32  1999           210 non-null    float64
 33  2000           210 non-null    float64
 34  2001           210 non-null    float64
 35  2002           210 non-null    float64
 36  2003           210 non-null    float64
 37  2004           210 non-null    float64
 38  2005           212 non-null    float64
 39  2006           212 non-null    float64
 40  2007           212 non-null    float64
 41  2008           214 non-null    float64
 42  2009           214 non-null    float64
 43  2010           214 non-null    float64
 44  2011           213 non-null    float64
 45  2012           213 non-null    float64
 46  2013           212 non-null    float64
 47  2014           212 non-null    float64
 48  2015           212 non-null    float64
 49  2016           212 non-null    float64
 50  2017           212 non-null    float64
 51  2018           212 non-null    float64
 52  2019           212 non-null    float64
 53  2020           212 non-null    float64
 54  2021           212 non-null    float64
 55  2022           212 non-null    float64
 56  2023           212 non-null    float64
 57  2024           212 non-null    float64
dtypes: float64(55), int64(1), object(2)
memory usage: 101.4+ KB
Informations about data in df_gdp:
 None

### Review Data Types in `df_gdp`

In [12]:
df_gdp.dtypes

CountryID          int64
Country           object
IndicatorName     object
1970             float64
1971             float64
1972             float64
1973             float64
1974             float64
1975             float64
1976             float64
1977             float64
1978             float64
1979             float64
1980             float64
1981             float64
1982             float64
1983             float64
1984             float64
1985             float64
1986             float64
1987             float64
1988             float64
1989             float64
1990             float64
1991             float64
1992             float64
1993             float64
1994             float64
1995             float64
1996             float64
1997             float64
1998             float64
1999             float64
2000             float64
2001             float64
2002             float64
2003             float64
2004             float64
2005             float64
2006             float64
2007             float64
2008             float64
2009             float64
2010             float64
2011             float64
2012             float64
2013             float64
2014             float64
2015             float64
2016             float64
2017             float64
2018             float64
2019             float64
2020             float64
2021             float64
2022             float64
2023             float64
2024             float64
dtype: object

### Check for Duplicate Country Entries

In [13]:
print("Duplicate countries:", df_gdp["Country"].duplicated().sum())

Duplicate countries: 0

### Remove Unneeded Indicator Column

In [14]:
df_gdp = df_gdp.drop(columns=["IndicatorName"])
df_gdp.head()

,CountryID,Country,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
7,4,Afghanistan,1.749,1.831,1.596,1.733,2.156,2.367,2.556,2.953,3.300,3.698,3.642,3.479,3.439,3.399,3.360,3.322,3.321,2.887,2.664,3.342,3.622,3.340,3.475,2.664,2.115,3.236,3.124,3.016,2.912,2.720,3.532,3.621,4.285,4.899,5.504,6.475,7.293,9.999,10.296,11.932,15.145,17.923,19.794,19.904,19.500,18.700,18.224,19.034,18.856,19.372,19.983,15.161,14.175,16.340,18.283
24,8,Albania,2.266,2.331,2.398,2.467,2.537,2.610,2.686,2.761,2.842,2.372,2.142,2.215,2.280,2.305,2.276,2.324,2.397,2.378,2.460,2.941,2.146,1.597,1.516,1.700,1.881,2.905,3.234,2.259,2.609,3.294,3.592,4.064,4.523,5.750,7.399,8.257,9.151,11.117,13.259,12.336,12.087,12.974,12.247,12.797,13.296,11.470,11.989,13.258,15.380,15.585,15.241,18.032,19.017,23.491,27.037
41,12,Algeria,5.155,5.364,7.176,9.230,13.260,15.556,17.750,20.991,26.374,33.201,42.252,44.265,45.095,48.702,52.828,57.866,62.923,64.334,58.655,55.344,61.751,46.565,49.106,50.847,42.331,41.971,46.836,48.806,49.566,50.800,58.101,59.413,61.516,73.482,91.914,107.047,123.084,142.483,180.384,150.317,177.785,218.332,227.144,229.701,238.943,187.494,180.764,189.881,194.554,193.460,164.873,186.232,225.638,247.626,266.972
58,20,Andorra,0.099,0.113,0.144,0.191,0.236,0.279,0.288,0.321,0.390,0.521,0.565,0.492,0.476,0.415,0.418,0.439,0.610,0.773,0.913,1.007,1.302,1.401,1.531,1.274,1.288,1.491,1.549,1.494,1.534,1.569,1.433,1.548,1.764,2.367,2.900,3.161,3.459,3.958,4.102,3.689,3.450,3.629,3.189,3.194,3.272,2.790,2.897,3.000,3.218,3.155,2.891,3.325,3.381,3.785,4.040
75,24,Angola,3.807,4.007,4.102,5.016,5.627,4.147,3.981,4.344,4.845,5.380,7.151,6.693,6.693,6.975,7.394,9.109,8.549,9.844,10.716,12.574,14.006,16.734,19.374,14.156,14.690,7.098,9.402,11.112,9.441,9.089,13.598,13.420,17.312,20.342,26.998,41.397,58.654,73.038,98.790,81.705,95.547,125.552,143.573,153.761,164.448,131.661,114.764,139.835,114.189,94.671,66.521,84.375,142.403,114.336,117.159

### Identify Year Columns and Summarize GDP Values

In [15]:
# ---------------------------------------------
# Summarize year-wise GDP columns
# ---------------------------------------------
year_columns = [col for col in df_gdp.columns if str(col).isdigit()]
print(year_columns)
df_gdp[year_columns].describe()

[1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
count,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000,188.000000,216.000000,211.000000,211.000000,211.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,212.000000,212.000000,212.000000,214.000000,214.000000,214.000000,213.000000,213.000000,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000
mean,18.297316,20.137642,23.171075,28.190615,31.932930,35.713936,38.587824,43.448556,51.474096,59.234829,66.091850,67.522225,66.999791,68.679706,70.618791,72.507449,83.583005,94.468428,105.659428,109.797383,110.628347,114.201038,122.087455,124.375900,133.253805,147.802814,150.935133,150.190667,149.394281,155.171433,159.719395,158.978100,165.384295,185.669790,209.089110,224.568061,243.501538,274.815094,299.421888,284.170421,311.204752,347.564573,354.980178,367.225769,376.852443,356.258566,362.130005,385.349585,409.234288,415.145425,404.419792,462.023057,480.742264,502.177656,522.491208
std,88.660193,96.287078,107.579195,123.908620,133.675141,147.019886,160.623459,179.653303,209.804504,234.463514,255.156205,274.536121,280.692567,301.508682,327.458277,349.030634,388.584096,427.135112,473.156706,496.720185,497.984818,529.511471,567.002744,599.201813,644.170958,694.848857,697.753104,708.026727,726.870288,774.355305,816.844270,821.814075,844.160059,899.783493,970.951619,1023.238389,1079.016459,1149.247063,1198.978973,1177.402165,1248.741637,1345.787130,1402.901957,1457.787981,1524.922197,1555.932937,1597.215681,1685.308830,1806.712200,1868.176077,1868.927026,2132.042302,2254.208069,2356.667947,2460.942386
min,0.003000,0.003000,0.003000,0.004000,0.004000,0.004000,0.004000,0.004000,0.004000,0.004000,0.004000,0.005000,0.004000,0.004000,0.004000,0.004000,0.004000,0.005000,0.008000,0.008000,0.010000,0.010000,0.011000,0.010000,0.011000,0.012000,0.012000,0.013000,0.013000,0.014000,0.014000,0.013000,0.016000,0.018000,0.022000,0.022000,0.023000,0.023000,0.030000,0.027000,0.031000,0.038000,0.037000,0.038000,0.038000,0.036000,0.041000,0.045000,0.048000,0.054000,0.052000,0.061000,0.054000,0.051000,0.056000
25%,0.219500,0.244500,0.285000,0.361500,0.410000,0.493000,0.531000,0.582000,0.669500,0.759500,0.877000,0.950500,0.898000,0.891000,0.916000,0.946000,1.120500,1.217500,1.303500,1.216250,1.754250,1.702500,1.531500,1.572000,1.497000,1.648000,1.800000,1.827750,1.757500,1.744000,1.683500,1.789500,1.920750,2.223500,2.723500,2.943750,3.286500,3.919250,5.123500,4.696250,4.758000,5.422000,5.487000,6.029500,6.332750,6.064000,5.973000,5.843500,6.327000,6.369500,6.217500,7.079500,7.059500,7.542500,8.480250
50%,1.067000,1.214000,1.301000,1.606000,2.128000,2.399000,2.681000,2.791000,3.098000,3.698000,4.138000,4.016000,4.085000,4.017000,4.438000,4.475000,4.392000,4.847000,4.789000,4.923000,5.313500,5.399000,5.644000,5.735000,5.548000,6.120500,7.160500,7.378500,6.903500,7.255500,7.896000,8.052500,8.201000,8.819500,10.214500,11.618500,13.773000,16.258000,18.680500,17.608000,19.593000,23.304000,23.237000,23.714000,23.330500,23.375000,23.907500,25.467000,26.675000,27.596500,25.417500,30.930000,31.797500,34.861000,36.904500
75%,6.018000,6.934000,8.145000,9.409500,12.386500,13.152000,14.261000,16.027000,18.349500,22.380000,27.087000,26.463000,26.708500,25.976500,24.628500,26.205500,28.224500,34.654000,36.011000,38.946000,37.266500,33.548000,35.139500,33.810000,39.095750,41.160250,45.237750,45.841500,43.199750,44.006250,43.827750,44.173500,46.912750,56.442250,67.108750,81.577250,91.884000,107.296250,130.988500,121.376750,137.890750,168.486000,179.117000,192.941000,200.969000,177.969750,170.142500,187.883750,196.697250,184.615250,166.425250,197.775500,225.531500,244.530000,253.349250
max,1073.303000,1164.850000,1279.110000,1425.376000,1545.243000,1684.904000,1873.412000,2081.826000,2351.599000,2627.333000,2857.307000,3207.041000,3343.789000,3634.038000,4037.613000,4338.979000,4579.631000,4855.215000,5236.438000,5641.580000,5963.144000,6158.129000,6520.327000,6858.559000,7287.236000,7639.749000,8073.122000,8577.552000,9062.817000,9631.172000,10250.952000,10581.929000,10929.108000,11456.450000,12217.196000,13039.197000,13815.583000,14474.228000,14769.862000,14478.067000,15048.971000,15599.732000,16253.970000,16880.683000,17608.138000,18295.019000,18804.913000,19612.102000,20656.516000,21540.000000,21375.300000,23725.600000,26054.600000,27811.500000,29298.000000

### Summarize Missing Values by Year

In [16]:
missing_summary = df_gdp[year_columns].isna().sum()
missing_summary = missing_summary.sort_values(ascending=True)
missing_summary.head(20)

1990    4
2010    6
2009    6
2008    6
2011    7
2012    7
2020    8
2019    8
2007    8
2005    8
2006    8
2017    8
2013    8
2016    8
2015    8
2014    8
2018    8
2024    8
2023    8
2022    8
dtype: int64

### Evaluate Missingness at the Country Level

In [17]:
df_gdp["Missing_Count"] = df_gdp[year_columns].isna().sum(axis=1)

df_gdp[["Country", "Missing_Count"]].sort_values(
    by="Missing_Count",
    ascending=False
).head()

                        Country  Missing_Count
3116                      Sudan             38
3031                South Sudan             38
871                     Curaçao             35
2930  Sint Maarten (Dutch part)             35
3638  Yemen Democratic (Former)             34

In [18]:
print("Total Countries:", len(df_gdp))
print("Countries with 0 missing values:", (df_gdp["Missing_Count"] == 0).sum())
print("Countries with more than 10 missing values:", (df_gdp["Missing_Count"] > 10).sum())

Total Countries: 220
Countries with 0 missing values: 179
Countries with more than 10 missing values: 41

### Descriptive Statistics for Country-Level Missing Values

In [19]:
df_gdp["Missing_Count"].describe()

count    220.000000
mean       4.327273
std        9.522968
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max       38.000000
Name: Missing_Count, dtype: float64

### Define the Analysis Window: 1980-2024

Earlier gaps are concentrated in post-independence and post-transition economies, so the analysis window is restricted to 1980-2024 for consistency and comparability.

In [20]:
analysis_years = [y for y in range(1980, 2025)]
analysis_years = [y for y in analysis_years if y in df_gdp.columns]

In [21]:
analysis_years

[1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024]

### Check Missing Values Within the Analysis Window

In [22]:
df_gdp["Missing_1980_2024"] = df_gdp[analysis_years].isna().sum(axis=1)

df_gdp["Missing_1980_2024"].describe()

count    220.000000
mean       2.827273
std        7.094096
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max       34.000000
Name: Missing_1980_2024, dtype: float64

In [23]:
df_gdp

,CountryID,Country,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Missing_Count,Missing_1980_2024
7,4,Afghanistan,1.749,1.831,1.596,1.733,2.156,2.367,2.556,2.953,3.300,3.698,3.642,3.479,3.439,3.399,3.360,3.322,3.321,2.887,2.664,3.342,3.622,3.340,3.475,2.664,2.115,3.236,3.124,3.016,2.912,2.720,3.532,3.621,4.285,4.899,5.504,6.475,7.293,9.999,10.296,11.932,15.145,17.923,19.794,19.904,19.500,18.700,18.224,19.034,18.856,19.372,19.983,15.161,14.175,16.340,18.283,0,0
24,8,Albania,2.266,2.331,2.398,2.467,2.537,2.610,2.686,2.761,2.842,2.372,2.142,2.215,2.280,2.305,2.276,2.324,2.397,2.378,2.460,2.941,2.146,1.597,1.516,1.700,1.881,2.905,3.234,2.259,2.609,3.294,3.592,4.064,4.523,5.750,7.399,8.257,9.151,11.117,13.259,12.336,12.087,12.974,12.247,12.797,13.296,11.470,11.989,13.258,15.380,15.585,15.241,18.032,19.017,23.491,27.037,0,0
41,12,Algeria,5.155,5.364,7.176,9.230,13.260,15.556,17.750,20.991,26.374,33.201,42.252,44.265,45.095,48.702,52.828,57.866,62.923,64.334,58.655,55.344,61.751,46.565,49.106,50.847,42.331,41.971,46.836,48.806,49.566,50.800,58.101,59.413,61.516,73.482,91.914,107.047,123.084,142.483,180.384,150.317,177.785,218.332,227.144,229.701,238.943,187.494,180.764,189.881,194.554,193.460,164.873,186.232,225.638,247.626,266.972,0,0
58,20,Andorra,0.099,0.113,0.144,0.191,0.236,0.279,0.288,0.321,0.390,0.521,0.565,0.492,0.476,0.415,0.418,0.439,0.610,0.773,0.913,1.007,1.302,1.401,1.531,1.274,1.288,1.491,1.549,1.494,1.534,1.569,1.433,1.548,1.764,2.367,2.900,3.161,3.459,3.958,4.102,3.689,3.450,3.629,3.189,3.194,3.272,2.790,2.897,3.000,3.218,3.155,2.891,3.325,3.381,3.785,4.040,0,0
75,24,Angola,3.807,4.007,4.102,5.016,5.627,4.147,3.981,4.344,4.845,5.380,7.151,6.693,6.693,6.975,7.394,9.109,8.549,9.844,10.716,12.574,14.006,16.734,19.374,14.156,14.690,7.098,9.402,11.112,9.441,9.089,13.598,13.420,17.312,20.342,26.998,41.397,58.654,73.038,98.790,81.705,95.547,125.552,143.573,153.761,164.448,131.661,114.764,139.835,114.189,94.671,66.521,84.375,142.403,114.336,117.159,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3638,720,Yemen Democratic (Former),0.154,0.142,0.159,0.130,0.138,0.140,0.182,0.225,0.271,0.292,0.355,0.408,0.487,0.513,0.547,0.533,0.463,0.477,0.502,0.578,0.697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34,34
3655,890,Yugoslavia (Former),14.554,15.802,16.485,21.472,29.706,33.279,37.563,45.673,54.338,68.198,69.959,68.930,62.827,64.373,69.045,73.375,79.473,84.643,87.765,94.419,88.294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34,34
3672,894,Zambia,1.544,1.574,1.852,2.350,2.895,2.658,2.814,2.767,3.098,3.827,4.315,4.016,4.275,3.992,3.194,2.772,2.105,2.108,3.471,3.956,3.795,3.377,3.307,3.274,3.657,3.807,3.597,4.303,3.538,3.404,3.601,4.094,4.194,4.902,6.221,8.329,12.762,14.060,17.914,15.332,20.264,23.455,25.502,28.042,27.145,21.245,20.965,25.874,26.311,23.309,18.138,22.096,29.164,27.578,25.303,0,0
3689,836,Zanzibar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.137,0.154,0.154,0.150,0.152,0.186,0.240,0.279,0.281,0.279,0.298,0.317,0.331,0.345,0.395,0.438,0.510,0.590,0.734,0.758,0.826,0.878,1.017,1.152,1.297,1.183,1.263,1.451,1.649,1.807,1.835,2.080,2.345,2.535,2.530,20,10
3706,716,Zimbabwe,2.337,2.702,3.336,4.104,4.938,5.421,5.357,5.411,5.413,6.422,8.257,9.935,10.590,9.628,7.877,8.720,9.616,10.426,12.086,12.781,13.560,12.652,10.434,10.135,10.656,11.063,13.466,13.854,9.706,9.225,8.721,8.659,8.215,7.747,7.416,7.189,7.049,6.958,6.348,9.666,12.042,14.102,17.115,19.091,19.496,22.300,25.640,30.720,36.814,39.295,33.747,36.001,38.966,44.476,45.719,0,0

### Remove Countries with Missing Values in 1980-2024

Create a clean balanced panel by keeping only countries with complete GDP observations across the selected period.

In [24]:
# ---------------------------------------------
# Create the clean balanced GDP panel
# ---------------------------------------------
df_clean = df_gdp[df_gdp["Missing_1980_2024"] == 0].copy() # making copy of gdp dataset into its clean version
df_clean

,CountryID,Country,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Missing_Count,Missing_1980_2024
7,4,Afghanistan,1.749,1.831,1.596,1.733,2.156,2.367,2.556,2.953,3.300,3.698,3.642,3.479,3.439,3.399,3.360,3.322,3.321,2.887,2.664,3.342,3.622,3.340,3.475,2.664,2.115,3.236,3.124,3.016,2.912,2.720,3.532,3.621,4.285,4.899,5.504,6.475,7.293,9.999,10.296,11.932,15.145,17.923,19.794,19.904,19.500,18.700,18.224,19.034,18.856,19.372,19.983,15.161,14.175,16.340,18.283,0,0
24,8,Albania,2.266,2.331,2.398,2.467,2.537,2.610,2.686,2.761,2.842,2.372,2.142,2.215,2.280,2.305,2.276,2.324,2.397,2.378,2.460,2.941,2.146,1.597,1.516,1.700,1.881,2.905,3.234,2.259,2.609,3.294,3.592,4.064,4.523,5.750,7.399,8.257,9.151,11.117,13.259,12.336,12.087,12.974,12.247,12.797,13.296,11.470,11.989,13.258,15.380,15.585,15.241,18.032,19.017,23.491,27.037,0,0
41,12,Algeria,5.155,5.364,7.176,9.230,13.260,15.556,17.750,20.991,26.374,33.201,42.252,44.265,45.095,48.702,52.828,57.866,62.923,64.334,58.655,55.344,61.751,46.565,49.106,50.847,42.331,41.971,46.836,48.806,49.566,50.800,58.101,59.413,61.516,73.482,91.914,107.047,123.084,142.483,180.384,150.317,177.785,218.332,227.144,229.701,238.943,187.494,180.764,189.881,194.554,193.460,164.873,186.232,225.638,247.626,266.972,0,0
58,20,Andorra,0.099,0.113,0.144,0.191,0.236,0.279,0.288,0.321,0.390,0.521,0.565,0.492,0.476,0.415,0.418,0.439,0.610,0.773,0.913,1.007,1.302,1.401,1.531,1.274,1.288,1.491,1.549,1.494,1.534,1.569,1.433,1.548,1.764,2.367,2.900,3.161,3.459,3.958,4.102,3.689,3.450,3.629,3.189,3.194,3.272,2.790,2.897,3.000,3.218,3.155,2.891,3.325,3.381,3.785,4.040,0,0
75,24,Angola,3.807,4.007,4.102,5.016,5.627,4.147,3.981,4.344,4.845,5.380,7.151,6.693,6.693,6.975,7.394,9.109,8.549,9.844,10.716,12.574,14.006,16.734,19.374,14.156,14.690,7.098,9.402,11.112,9.441,9.089,13.598,13.420,17.312,20.342,26.998,41.397,58.654,73.038,98.790,81.705,95.547,125.552,143.573,153.761,164.448,131.661,114.764,139.835,114.189,94.671,66.521,84.375,142.403,114.336,117.159,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3553,548,Vanuatu,0.038,0.041,0.055,0.067,0.066,0.080,0.078,0.081,0.099,0.130,0.124,0.108,0.107,0.115,0.139,0.133,0.129,0.137,0.161,0.158,0.171,0.204,0.213,0.219,0.240,0.273,0.283,0.285,0.260,0.265,0.265,0.255,0.264,0.314,0.365,0.395,0.439,0.526,0.591,0.593,0.671,0.770,0.748,0.758,0.774,0.760,0.804,0.880,0.915,0.937,0.909,0.982,1.031,1.090,1.092,0,0
3570,862,Venezuela (Bolivarian Republic of),13.864,15.227,16.744,20.000,30.465,32.093,36.744,42.326,46.047,56.512,69.070,77.674,79.302,79.070,58.005,60.000,58.515,46.483,58.276,41.451,47.045,51.720,58.465,58.101,57.164,74.892,68.257,85.837,91.337,97.974,117.147,122.912,92.889,83.529,112.451,145.514,183.477,230.364,315.600,329.419,393.806,316.483,381.286,371.338,363.090,343.661,287.807,247.051,203.127,149.256,105.889,111.775,129.303,139.459,150.494,0,0
3587,704,Viet Nam,2.775,3.024,3.237,3.350,3.605,3.896,4.541,5.413,6.532,7.140,2.396,1.885,2.190,3.289,5.069,4.758,5.017,5.272,5.736,6.241,6.417,7.578,9.867,13.181,16.281,20.736,24.658,26.844,27.210,28.684,31.173,32.685,35.064,39.553,49.494,57.633,69.618,85.174,114.402,128.331,147.201,172.595,195.591,213.709,233.451,239.258,257.096,281.354,310.106,334.365,346.616,366.475,413.445,433.858,476.388,0,0
3672,894,Zambia,1.544,1.574,1.852,2.350,2.895,2.658,2.814,2.767,3.098,3.827,4.315,4.016,4.275,3.992,3.194,2.772,2.105,2.108,3.471,3.956,3.795,3.377,3.307,3.274,3.657,3.807,3.597,4.303,3.538,3.404,3.601,4.094,4.194,4.902,6.221,8.329,12.762,14.060,17.914,15.332,20.264,23.455,25.502,28.042,27.145,21.245,20.965,25.874,26.311,23.309,18.138,22.096,29.164,27.578,25.303,0,0
3706,716,Zimbabwe,2.337,2.702,3.336,4.104,4.938,5.421,5.357,5.411,5.413,6.422,8.257,9.935,10.590,9.628,7.877,8.720,9.616,10.426,12.086,12.781,13.560,12.652,10.434,10.135,10.656,11.063,13.466,13.854,9.706,9.225,8.721,8.659,8.215,7.747,7.416,7.189,7.049,6.958,6.348,9.666,12.042,14.102,17.115,19.091,19.496,22.300,25.640,30.720,36.814,39.295,33.747,36.001,38.966,44.476,45.719,0,0

In [25]:
print("Shape of dataset after cleaning: ", df_clean.shape) # checking count of rows and columns in the cleaned dataframe
print("Statiscal information of cleaned dataset: ")
df_clean.describe()

Shape of dataset after cleaning:  (179, 59)
Statiscal information of cleaned dataset:

,CountryID,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Missing_Count,Missing_1980_2024
count,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.00000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.0,179.0
mean,420.910615,16.495916,18.281659,21.091849,25.713408,29.567983,33.091352,36.050223,40.730374,48.470620,56.132201,63.051313,64.709324,63.906017,65.468732,67.783877,69.861380,81.687190,93.257184,105.029419,109.923966,122.743575,129.394000,139.28957,142.303911,152.373615,169.322430,173.005609,172.012134,171.825810,179.201927,184.210603,182.918911,189.930475,212.751570,238.728089,257.787318,278.138453,312.170212,340.846838,326.159737,356.277229,394.275341,402.164352,413.659402,426.456737,407.135698,414.775553,439.882620,467.367916,473.937782,462.505587,527.586525,546.663168,571.983324,594.929765,0.0,0.0
std,248.051718,85.052627,92.783195,103.497490,118.590116,129.305192,142.024466,156.656637,175.946658,205.972861,230.989953,252.223513,273.266300,278.790389,300.099979,328.149129,350.963409,392.797659,433.142765,480.686761,506.243751,541.965169,572.322103,613.20394,648.318907,695.579378,750.253234,753.321877,764.508588,785.188107,836.601627,882.599879,888.021461,912.113640,971.901142,1048.348166,1109.407853,1169.188199,1243.932313,1301.737775,1280.550518,1356.741389,1456.332177,1517.864685,1573.885173,1648.636223,1686.146845,1731.312070,1826.027984,1957.763302,2024.703846,2026.490263,2311.401856,2442.823118,2555.186262,2668.285119,0.0,0.0
min,4.000000,0.003000,0.003000,0.003000,0.004000,0.004000,0.004000,0.004000,0.004000,0.004000,0.004000,0.004000,0.005000,0.004000,0.004000,0.004000,0.004000,0.004000,0.005000,0.008000,0.008000,0.010000,0.010000,0.01100,0.010000,0.011000,0.012000,0.012000,0.013000,0.013000,0.014000,0.014000,0.013000,0.016000,0.018000,0.022000,0.022000,0.023000,0.023000,0.030000,0.027000,0.031000,0.038000,0.037000,0.038000,0.038000,0.036000,0.041000,0.045000,0.048000,0.054000,0.052000,0.061000,0.054000,0.051000,0.056000,0.0,0.0
25%,206.000000,0.212000,0.238000,0.285000,0.361500,0.410000,0.493000,0.530000,0.570500,0.655000,0.746000,0.845000,0.916500,0.879000,0.879500,0.843000,0.882500,1.088500,1.170000,1.232500,1.197000,1.278000,1.357500,1.47600,1.422000,1.368000,1.589000,1.717000,1.787500,1.699000,1.735500,1.629000,1.699000,1.805000,2.161500,2.507000,2.941500,3.375000,3.987500,4.582500,4.117500,4.460500,4.818000,5.305500,5.538000,5.746500,5.513000,5.588000,5.791500,6.068000,6.094500,5.615000,6.611500,7.002000,7.232000,7.627500,0.0,0.0
50%,422.000000,1.052000,1.138000,1.293000,1.602000,1.996000,2.367000,2.640000,2.767000,3.026000,3.522000,4.119000,3.876000,3.970000,3.992000,4.216000,4.425000,4.129000,4.315000,4.747000,4.855000,4.909000,5.252000,5.73400,5.946000,6.110000,6.715000,7.244000,7.472000,6.998000,7.582000,8.345000,8.318000,8.215000,8.769000,10.175000,11.244000,12.762000,14.375000,17.987000,16.146000,18.448000,21.357000,22.388000,21.991000,23.211000,22.300000,23.624000,25.060000,26.311000,26.881000,25.280000,30.634000,31.725000,35.051000,37.094000,0.0,0.0
75%,622.000000,5.766500,6.713500,7.672000,9.039500,11.715000,12.852500,13.842000,15.450500,18.079500,22.141500,25.371000,25.787000,26.466000,24.432500,23.863000,24.571000,27.524000,33.050000,33.709500,36.801000,39.619500,41.765000,46.89150,50.733500,51.610000,58.261000,61.765500,63.723000,57.692000,59.647000,66.009000,70.849000,71.463000,80.018500,97.040500,110.259000,122.554000,149.231500,179.644500,172.762000,185.772000,223.425000,222.572500,232.169500,233.681500,213.912000,222.541500,215.935500,242.781000,245.896500,240.826500,271.317000,283.812500,293.687000,294.013000,0.0,0.0
max,894.000000,1073.303000,1164.850000,1279.110000,1425.376000,1545.243000,1684.904000,1873.412000,2081.826000,2351.599000,2627.333000,2857.307000,3207.041000,3343.789000,3634.038000,4037.613000,4338.979000,4579.631000,4855.215000,5236.438000,5641.580000,5963.144000,6158.129000,6520.32700,6858.559000,7287.236000,7639.749000,8073.122000,8577.552000,9062.817000,9631.172000,10250.952000,10581.929000,10929.108000,11456.450000,12217.196000,13039.197000,13815.583000,14474.228000,14769.862000,14478.067000,15048.971000,15599.732000,16253.970000,16880.683000,17608.138000,18295.019000,18804.913000,19612.102000,20656.516000,21540.000000,21375.300000,23725.600000,26054.600000,27811.500000,29298.000000,0.0,0.0

In [26]:
print("Total remaining missing values:",
      df_clean[analysis_years].isna().sum().sum())

df_clean

Total remaining missing values: 0

,CountryID,Country,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Missing_Count,Missing_1980_2024
7,4,Afghanistan,1.749,1.831,1.596,1.733,2.156,2.367,2.556,2.953,3.300,3.698,3.642,3.479,3.439,3.399,3.360,3.322,3.321,2.887,2.664,3.342,3.622,3.340,3.475,2.664,2.115,3.236,3.124,3.016,2.912,2.720,3.532,3.621,4.285,4.899,5.504,6.475,7.293,9.999,10.296,11.932,15.145,17.923,19.794,19.904,19.500,18.700,18.224,19.034,18.856,19.372,19.983,15.161,14.175,16.340,18.283,0,0
24,8,Albania,2.266,2.331,2.398,2.467,2.537,2.610,2.686,2.761,2.842,2.372,2.142,2.215,2.280,2.305,2.276,2.324,2.397,2.378,2.460,2.941,2.146,1.597,1.516,1.700,1.881,2.905,3.234,2.259,2.609,3.294,3.592,4.064,4.523,5.750,7.399,8.257,9.151,11.117,13.259,12.336,12.087,12.974,12.247,12.797,13.296,11.470,11.989,13.258,15.380,15.585,15.241,18.032,19.017,23.491,27.037,0,0
41,12,Algeria,5.155,5.364,7.176,9.230,13.260,15.556,17.750,20.991,26.374,33.201,42.252,44.265,45.095,48.702,52.828,57.866,62.923,64.334,58.655,55.344,61.751,46.565,49.106,50.847,42.331,41.971,46.836,48.806,49.566,50.800,58.101,59.413,61.516,73.482,91.914,107.047,123.084,142.483,180.384,150.317,177.785,218.332,227.144,229.701,238.943,187.494,180.764,189.881,194.554,193.460,164.873,186.232,225.638,247.626,266.972,0,0
58,20,Andorra,0.099,0.113,0.144,0.191,0.236,0.279,0.288,0.321,0.390,0.521,0.565,0.492,0.476,0.415,0.418,0.439,0.610,0.773,0.913,1.007,1.302,1.401,1.531,1.274,1.288,1.491,1.549,1.494,1.534,1.569,1.433,1.548,1.764,2.367,2.900,3.161,3.459,3.958,4.102,3.689,3.450,3.629,3.189,3.194,3.272,2.790,2.897,3.000,3.218,3.155,2.891,3.325,3.381,3.785,4.040,0,0
75,24,Angola,3.807,4.007,4.102,5.016,5.627,4.147,3.981,4.344,4.845,5.380,7.151,6.693,6.693,6.975,7.394,9.109,8.549,9.844,10.716,12.574,14.006,16.734,19.374,14.156,14.690,7.098,9.402,11.112,9.441,9.089,13.598,13.420,17.312,20.342,26.998,41.397,58.654,73.038,98.790,81.705,95.547,125.552,143.573,153.761,164.448,131.661,114.764,139.835,114.189,94.671,66.521,84.375,142.403,114.336,117.159,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3553,548,Vanuatu,0.038,0.041,0.055,0.067,0.066,0.080,0.078,0.081,0.099,0.130,0.124,0.108,0.107,0.115,0.139,0.133,0.129,0.137,0.161,0.158,0.171,0.204,0.213,0.219,0.240,0.273,0.283,0.285,0.260,0.265,0.265,0.255,0.264,0.314,0.365,0.395,0.439,0.526,0.591,0.593,0.671,0.770,0.748,0.758,0.774,0.760,0.804,0.880,0.915,0.937,0.909,0.982,1.031,1.090,1.092,0,0
3570,862,Venezuela (Bolivarian Republic of),13.864,15.227,16.744,20.000,30.465,32.093,36.744,42.326,46.047,56.512,69.070,77.674,79.302,79.070,58.005,60.000,58.515,46.483,58.276,41.451,47.045,51.720,58.465,58.101,57.164,74.892,68.257,85.837,91.337,97.974,117.147,122.912,92.889,83.529,112.451,145.514,183.477,230.364,315.600,329.419,393.806,316.483,381.286,371.338,363.090,343.661,287.807,247.051,203.127,149.256,105.889,111.775,129.303,139.459,150.494,0,0
3587,704,Viet Nam,2.775,3.024,3.237,3.350,3.605,3.896,4.541,5.413,6.532,7.140,2.396,1.885,2.190,3.289,5.069,4.758,5.017,5.272,5.736,6.241,6.417,7.578,9.867,13.181,16.281,20.736,24.658,26.844,27.210,28.684,31.173,32.685,35.064,39.553,49.494,57.633,69.618,85.174,114.402,128.331,147.201,172.595,195.591,213.709,233.451,239.258,257.096,281.354,310.106,334.365,346.616,366.475,413.445,433.858,476.388,0,0
3672,894,Zambia,1.544,1.574,1.852,2.350,2.895,2.658,2.814,2.767,3.098,3.827,4.315,4.016,4.275,3.992,3.194,2.772,2.105,2.108,3.471,3.956,3.795,3.377,3.307,3.274,3.657,3.807,3.597,4.303,3.538,3.404,3.601,4.094,4.194,4.902,6.221,8.329,12.762,14.060,17.914,15.332,20.264,23.455,25.502,28.042,27.145,21.245,20.965,25.874,26.311,23.309,18.138,22.096,29.164,27.578,25.303,0,0
3706,716,Zimbabwe,2.337,2.702,3.336,4.104,4.938,5.421,5.357,5.411,5.413,6.422,8.257,9.935,10.590,9.628,7.877,8.720,9.616,10.426,12.086,12.781,13.560,12.652,10.434,10.135,10.656,11.063,13.466,13.854,9.706,9.225,8.721,8.659,8.215,7.747,7.416,7.189,7.049,6.958,6.348,9.666,12.042,14.102,17.115,19.091,19.496,22.300,25.640,30.720,36.814,39.295,33.747,36.001,38.966,44.476,45.719,0,0

The cleaned GDP panel contains no remaining missing values for the 1980-2024 analysis period. In the GDP-only dataset, 622 missing values were present before this filtering step.

### Drop Temporary Helper Columns

In [27]:
df_clean = df_clean.drop(columns=["Missing_Count", "Missing_1980_2024"])

In [28]:
# Resetting Index
df_clean = df_clean.reset_index(drop=True)
df_clean

,CountryID,Country,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,4,Afghanistan,1.749,1.831,1.596,1.733,2.156,2.367,2.556,2.953,3.300,3.698,3.642,3.479,3.439,3.399,3.360,3.322,3.321,2.887,2.664,3.342,3.622,3.340,3.475,2.664,2.115,3.236,3.124,3.016,2.912,2.720,3.532,3.621,4.285,4.899,5.504,6.475,7.293,9.999,10.296,11.932,15.145,17.923,19.794,19.904,19.500,18.700,18.224,19.034,18.856,19.372,19.983,15.161,14.175,16.340,18.283
1,8,Albania,2.266,2.331,2.398,2.467,2.537,2.610,2.686,2.761,2.842,2.372,2.142,2.215,2.280,2.305,2.276,2.324,2.397,2.378,2.460,2.941,2.146,1.597,1.516,1.700,1.881,2.905,3.234,2.259,2.609,3.294,3.592,4.064,4.523,5.750,7.399,8.257,9.151,11.117,13.259,12.336,12.087,12.974,12.247,12.797,13.296,11.470,11.989,13.258,15.380,15.585,15.241,18.032,19.017,23.491,27.037
2,12,Algeria,5.155,5.364,7.176,9.230,13.260,15.556,17.750,20.991,26.374,33.201,42.252,44.265,45.095,48.702,52.828,57.866,62.923,64.334,58.655,55.344,61.751,46.565,49.106,50.847,42.331,41.971,46.836,48.806,49.566,50.800,58.101,59.413,61.516,73.482,91.914,107.047,123.084,142.483,180.384,150.317,177.785,218.332,227.144,229.701,238.943,187.494,180.764,189.881,194.554,193.460,164.873,186.232,225.638,247.626,266.972
3,20,Andorra,0.099,0.113,0.144,0.191,0.236,0.279,0.288,0.321,0.390,0.521,0.565,0.492,0.476,0.415,0.418,0.439,0.610,0.773,0.913,1.007,1.302,1.401,1.531,1.274,1.288,1.491,1.549,1.494,1.534,1.569,1.433,1.548,1.764,2.367,2.900,3.161,3.459,3.958,4.102,3.689,3.450,3.629,3.189,3.194,3.272,2.790,2.897,3.000,3.218,3.155,2.891,3.325,3.381,3.785,4.040
4,24,Angola,3.807,4.007,4.102,5.016,5.627,4.147,3.981,4.344,4.845,5.380,7.151,6.693,6.693,6.975,7.394,9.109,8.549,9.844,10.716,12.574,14.006,16.734,19.374,14.156,14.690,7.098,9.402,11.112,9.441,9.089,13.598,13.420,17.312,20.342,26.998,41.397,58.654,73.038,98.790,81.705,95.547,125.552,143.573,153.761,164.448,131.661,114.764,139.835,114.189,94.671,66.521,84.375,142.403,114.336,117.159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,548,Vanuatu,0.038,0.041,0.055,0.067,0.066,0.080,0.078,0.081,0.099,0.130,0.124,0.108,0.107,0.115,0.139,0.133,0.129,0.137,0.161,0.158,0.171,0.204,0.213,0.219,0.240,0.273,0.283,0.285,0.260,0.265,0.265,0.255,0.264,0.314,0.365,0.395,0.439,0.526,0.591,0.593,0.671,0.770,0.748,0.758,0.774,0.760,0.804,0.880,0.915,0.937,0.909,0.982,1.031,1.090,1.092
175,862,Venezuela (Bolivarian Republic of),13.864,15.227,16.744,20.000,30.465,32.093,36.744,42.326,46.047,56.512,69.070,77.674,79.302,79.070,58.005,60.000,58.515,46.483,58.276,41.451,47.045,51.720,58.465,58.101,57.164,74.892,68.257,85.837,91.337,97.974,117.147,122.912,92.889,83.529,112.451,145.514,183.477,230.364,315.600,329.419,393.806,316.483,381.286,371.338,363.090,343.661,287.807,247.051,203.127,149.256,105.889,111.775,129.303,139.459,150.494
176,704,Viet Nam,2.775,3.024,3.237,3.350,3.605,3.896,4.541,5.413,6.532,7.140,2.396,1.885,2.190,3.289,5.069,4.758,5.017,5.272,5.736,6.241,6.417,7.578,9.867,13.181,16.281,20.736,24.658,26.844,27.210,28.684,31.173,32.685,35.064,39.553,49.494,57.633,69.618,85.174,114.402,128.331,147.201,172.595,195.591,213.709,233.451,239.258,257.096,281.354,310.106,334.365,346.616,366.475,413.445,433.858,476.388
177,894,Zambia,1.544,1.574,1.852,2.350,2.895,2.658,2.814,2.767,3.098,3.827,4.315,4.016,4.275,3.992,3.194,2.772,2.105,2.108,3.471,3.956,3.795,3.377,3.307,3.274,3.657,3.807,3.597,4.303,3.538,3.404,3.601,4.094,4.194,4.902,6.221,8.329,12.762,14.060,17.914,15.332,20.264,23.455,25.502,28.042,27.145,21.245,20.965,25.874,26.311,23.309,18.138,22.096,29.164,27.578,25.303
178,716,Zimbabwe,2.337,2.702,3.336,4.104,4.938,5.421,5.357,5.411,5.413,6.422,8.257,9.935,10.590,9.628,7.877,8.720,9.616,10.426,12.086,12.781,13.560,12.652,10.434,10.135,10.656,11.063,13.466,13.854,9.706,9.225,8.721,8.659,8.215,7.747,7.416,7.189,7.049,6.958,6.348,9.666,12.042,14.102,17.115,19.091,19.496,22.300,25.640,30.720,36.814,39.295,33.747,36.001,38.966,44.476,45.719

### Confirm Final Clean Dataset Shape

In [29]:
print("Final Clean Dataset Shape:", df_clean.shape)

Final Clean Dataset Shape: (179, 57)

### Save the Cleaned GDP Dataset

Export the cleaned panel to Excel for reuse in later analysis.

In [30]:
df_clean.to_excel("C:\Projects\DAP\gdp-growth-analysis\data\data_gdp.xlsx", index=False)

### Feature Engineering

Construct interpretable measures of economic change, expansion, and stability from the cleaned GDP panel.

### Define Annual GDP Growth Function

Compute year-over-year GDP growth for a selected year relative to the previous year.

In [31]:
# ---------------------------------------------
# Feature engineering helper functions
# ---------------------------------------------
def compute_growth(df, year):
    """
    Computes GDP growth (%) for a given year relative to previous year.
    Returns a pandas Series.
    """
    if year - 1 not in df.columns:
        raise ValueError("Previous year not available in dataset.")
    
    growth = ((df[year] - df[year - 1]) / df[year - 1]) * 100
    return growth

Annual Growth Formula:

`Growth(t) = ((GDP(t) - GDP(t-1)) / GDP(t-1)) x 100`

### Example: Growth Rate for 2020

In [32]:
growth_2020 = compute_growth(df_clean, 2020)
growth_2020.head()

0     3.154037
1    -2.207251
2   -14.776698
3    -8.367670
4   -29.734554
dtype: float64

### Define Multi-Year Growth Function

Compute total percentage growth between any two selected years.

In [33]:
def compute_growth_between(df, start_year, end_year):
    """
    Computes total percentage growth between two selected years.
    """
    if start_year not in df.columns or end_year not in df.columns:
        raise ValueError("Selected years not found in dataset.")
    
    growth = ((df[end_year] - df[start_year]) / df[start_year]) * 100
    return growth

### Example: Growth Between 2005 and 2024

In [34]:
growth_2005_2024 = compute_growth_between(df_clean, 2005, 2024)
growth_2005_2024.head()

0    182.362934
1    227.443381
2    149.396994
3     27.807656
4    183.013262
dtype: float64

### CAGR: Compound Annual Growth Rate

CAGR is used to summarize long-run growth over extended periods in a more stable and interpretable form than simple percentage change.

In [35]:
# CAGR = [(GDP1980 ​/ GDP2024​​) ^ (1/n)] − 1

n_years = 2024 - 1980

df_clean["CAGR"] = (
    (df_clean[2024] / df_clean[1980]) ** (1 / n_years) - 1
) * 100

df_clean

,CountryID,Country,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,CAGR
0,4,Afghanistan,1.749,1.831,1.596,1.733,2.156,2.367,2.556,2.953,3.300,3.698,3.642,3.479,3.439,3.399,3.360,3.322,3.321,2.887,2.664,3.342,3.622,3.340,3.475,2.664,2.115,3.236,3.124,3.016,2.912,2.720,3.532,3.621,4.285,4.899,5.504,6.475,7.293,9.999,10.296,11.932,15.145,17.923,19.794,19.904,19.500,18.700,18.224,19.034,18.856,19.372,19.983,15.161,14.175,16.340,18.283,3.734966
1,8,Albania,2.266,2.331,2.398,2.467,2.537,2.610,2.686,2.761,2.842,2.372,2.142,2.215,2.280,2.305,2.276,2.324,2.397,2.378,2.460,2.941,2.146,1.597,1.516,1.700,1.881,2.905,3.234,2.259,2.609,3.294,3.592,4.064,4.523,5.750,7.399,8.257,9.151,11.117,13.259,12.336,12.087,12.974,12.247,12.797,13.296,11.470,11.989,13.258,15.380,15.585,15.241,18.032,19.017,23.491,27.037,5.931687
2,12,Algeria,5.155,5.364,7.176,9.230,13.260,15.556,17.750,20.991,26.374,33.201,42.252,44.265,45.095,48.702,52.828,57.866,62.923,64.334,58.655,55.344,61.751,46.565,49.106,50.847,42.331,41.971,46.836,48.806,49.566,50.800,58.101,59.413,61.516,73.482,91.914,107.047,123.084,142.483,180.384,150.317,177.785,218.332,227.144,229.701,238.943,187.494,180.764,189.881,194.554,193.460,164.873,186.232,225.638,247.626,266.972,4.278764
3,20,Andorra,0.099,0.113,0.144,0.191,0.236,0.279,0.288,0.321,0.390,0.521,0.565,0.492,0.476,0.415,0.418,0.439,0.610,0.773,0.913,1.007,1.302,1.401,1.531,1.274,1.288,1.491,1.549,1.494,1.534,1.569,1.433,1.548,1.764,2.367,2.900,3.161,3.459,3.958,4.102,3.689,3.450,3.629,3.189,3.194,3.272,2.790,2.897,3.000,3.218,3.155,2.891,3.325,3.381,3.785,4.040,4.572299
4,24,Angola,3.807,4.007,4.102,5.016,5.627,4.147,3.981,4.344,4.845,5.380,7.151,6.693,6.693,6.975,7.394,9.109,8.549,9.844,10.716,12.574,14.006,16.734,19.374,14.156,14.690,7.098,9.402,11.112,9.441,9.089,13.598,13.420,17.312,20.342,26.998,41.397,58.654,73.038,98.790,81.705,95.547,125.552,143.573,153.761,164.448,131.661,114.764,139.835,114.189,94.671,66.521,84.375,142.403,114.336,117.159,6.561470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,548,Vanuatu,0.038,0.041,0.055,0.067,0.066,0.080,0.078,0.081,0.099,0.130,0.124,0.108,0.107,0.115,0.139,0.133,0.129,0.137,0.161,0.158,0.171,0.204,0.213,0.219,0.240,0.273,0.283,0.285,0.260,0.265,0.265,0.255,0.264,0.314,0.365,0.395,0.439,0.526,0.591,0.593,0.671,0.770,0.748,0.758,0.774,0.760,0.804,0.880,0.915,0.937,0.909,0.982,1.031,1.090,1.092,5.068552
175,862,Venezuela (Bolivarian Republic of),13.864,15.227,16.744,20.000,30.465,32.093,36.744,42.326,46.047,56.512,69.070,77.674,79.302,79.070,58.005,60.000,58.515,46.483,58.276,41.451,47.045,51.720,58.465,58.101,57.164,74.892,68.257,85.837,91.337,97.974,117.147,122.912,92.889,83.529,112.451,145.514,183.477,230.364,315.600,329.419,393.806,316.483,381.286,371.338,363.090,343.661,287.807,247.051,203.127,149.256,105.889,111.775,129.303,139.459,150.494,1.785764
176,704,Viet Nam,2.775,3.024,3.237,3.350,3.605,3.896,4.541,5.413,6.532,7.140,2.396,1.885,2.190,3.289,5.069,4.758,5.017,5.272,5.736,6.241,6.417,7.578,9.867,13.181,16.281,20.736,24.658,26.844,27.210,28.684,31.173,32.685,35.064,39.553,49.494,57.633,69.618,85.174,114.402,128.331,147.201,172.595,195.591,213.709,233.451,239.258,257.096,281.354,310.106,334.365,346.616,366.475,413.445,433.858,476.388,12.781546
177,894,Zambia,1.544,1.574,1.852,2.350,2.895,2.658,2.814,2.767,3.098,3.827,4.315,4.016,4.275,3.992,3.194,2.772,2.105,2.108,3.471,3.956,3.795,3.377,3.307,3.274,3.657,3.807,3.597,4.303,3.538,3.404,3.601,4.094,4.194,4.902,6.221,8.329,12.762,14.060,17.914,15.332,20.264,23.455,25.502,28.042,27.145,21.245,20.965,25.874,26.311,23.309,18.138,22.096,29.164,27.578,25.303,4.101956
178,716,Zimbabwe,2.337,2.702,3.336,4.104,4.938,5.421,5.357,5.411,5.413,6.422,8.257,9.935,10.590,9.628,7.877,8.720,9.616,10.426,12.086,12.781,13.560,12.652,10.434,10.135,10.656,11.063,13.466,13.854,9.706,9.225,8.721,8.659,8.215,7.747,7.416,7.189,7.049,6.958,6.348,9.666,12.042,14.102,17.115,19.091,19.496,22.300,25.640,30.720,36.814,39.295,33.747,36.001,38.966,44.476,45.719,3.966303

### Define CAGR Function

This measure captures the constant annualized growth rate required to move from the starting GDP level to the ending GDP level over the selected time horizon.

CAGR (Compound Annual Growth Rate) measures the constant annual growth rate that would take GDP from its starting value to its ending value over a specified period. It is especially useful for long-run comparisons because it smooths irregular year-to-year variation into a single interpretable rate.

In [36]:
def compute_cagr(df, start_year, end_year):
    """
    Computes CAGR (%) between two years.
    """
    n_years = end_year - start_year
    
    cagr = ((df[end_year] / df[start_year]) ** (1 / n_years) - 1) * 100
    return cagr

In [37]:
cagr_1980_2024 = compute_cagr(df_clean, 1980, 2024)
cagr_1980_2024

0       3.734966
1       5.931687
2       4.278764
3       4.572299
4       6.561470
         ...
174     5.068552
175     1.785764
176    12.781546
177     4.101956
178     3.966303
Length: 179, dtype: float64

### Economic Expansion Multiplier

Measure how many times larger an economy became between the base year and the final year.

In [38]:
df_clean["GDP_Multiplier"] = df_clean[2024] / df_clean[1980]

This metric answers a direct scale question: how many times larger is the economy in 2024 relative to 1980?

In [39]:
df_clean[["Country", "GDP_Multiplier"]]

                                Country  GDP_Multiplier
0                           Afghanistan        5.020044
1                               Albania       12.622316
2                               Algeria        6.318565
3                               Andorra        7.150442
4                                Angola       16.383583
..                                  ...             ...
174                             Vanuatu        8.806452
175  Venezuela (Bolivarian Republic of)        2.178862
176                            Viet Nam      198.826377
177                              Zambia        5.863963
178                            Zimbabwe        5.536999

[179 rows x 2 columns]

### Growth Volatility

Growth volatility is defined as the standard deviation of annual GDP growth rates across the analysis period. It serves as a simple indicator of macroeconomic stability.

In [40]:
# ---------------------------------------------
# Volatility calculation helper
# ---------------------------------------------
def compute_growth_volatility(df, years):
    growth_rates = []
    
    for year in years[1:]:
        growth = ((df[year] - df[year - 1]) / df[year - 1]) * 100
        growth_rates.append(growth)
    
    growth_df = pd.concat(growth_rates, axis=1)
    return growth_df.std(axis=1)

df_clean["Growth_Volatility"] = compute_growth_volatility(df_clean, analysis_years)

Interpretation:

- High volatility indicates less stable and more erratic growth patterns.
- Low volatility indicates a more stable macroeconomic trajectory.

In [41]:
df_clean[["Country", "Growth_Volatility"]]

                                Country  Growth_Volatility
0                           Afghanistan          15.133276
1                               Albania          15.094975
2                               Algeria          11.745418
3                               Andorra          12.653118
4                                Angola          23.935119
..                                  ...                ...
174                             Vanuatu           7.903286
175  Venezuela (Bolivarian Republic of)          18.280182
176                            Viet Nam          13.221009
177                              Zambia          19.438674
178                            Zimbabwe          14.014585

[179 rows x 2 columns]

In [42]:
df_clean # dataset with new features added - CAGR, GDP_Multiplier, Growth_Votatility

,CountryID,Country,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,CAGR,GDP_Multiplier,Growth_Volatility
0,4,Afghanistan,1.749,1.831,1.596,1.733,2.156,2.367,2.556,2.953,3.300,3.698,3.642,3.479,3.439,3.399,3.360,3.322,3.321,2.887,2.664,3.342,3.622,3.340,3.475,2.664,2.115,3.236,3.124,3.016,2.912,2.720,3.532,3.621,4.285,4.899,5.504,6.475,7.293,9.999,10.296,11.932,15.145,17.923,19.794,19.904,19.500,18.700,18.224,19.034,18.856,19.372,19.983,15.161,14.175,16.340,18.283,3.734966,5.020044,15.133276
1,8,Albania,2.266,2.331,2.398,2.467,2.537,2.610,2.686,2.761,2.842,2.372,2.142,2.215,2.280,2.305,2.276,2.324,2.397,2.378,2.460,2.941,2.146,1.597,1.516,1.700,1.881,2.905,3.234,2.259,2.609,3.294,3.592,4.064,4.523,5.750,7.399,8.257,9.151,11.117,13.259,12.336,12.087,12.974,12.247,12.797,13.296,11.470,11.989,13.258,15.380,15.585,15.241,18.032,19.017,23.491,27.037,5.931687,12.622316,15.094975
2,12,Algeria,5.155,5.364,7.176,9.230,13.260,15.556,17.750,20.991,26.374,33.201,42.252,44.265,45.095,48.702,52.828,57.866,62.923,64.334,58.655,55.344,61.751,46.565,49.106,50.847,42.331,41.971,46.836,48.806,49.566,50.800,58.101,59.413,61.516,73.482,91.914,107.047,123.084,142.483,180.384,150.317,177.785,218.332,227.144,229.701,238.943,187.494,180.764,189.881,194.554,193.460,164.873,186.232,225.638,247.626,266.972,4.278764,6.318565,11.745418
3,20,Andorra,0.099,0.113,0.144,0.191,0.236,0.279,0.288,0.321,0.390,0.521,0.565,0.492,0.476,0.415,0.418,0.439,0.610,0.773,0.913,1.007,1.302,1.401,1.531,1.274,1.288,1.491,1.549,1.494,1.534,1.569,1.433,1.548,1.764,2.367,2.900,3.161,3.459,3.958,4.102,3.689,3.450,3.629,3.189,3.194,3.272,2.790,2.897,3.000,3.218,3.155,2.891,3.325,3.381,3.785,4.040,4.572299,7.150442,12.653118
4,24,Angola,3.807,4.007,4.102,5.016,5.627,4.147,3.981,4.344,4.845,5.380,7.151,6.693,6.693,6.975,7.394,9.109,8.549,9.844,10.716,12.574,14.006,16.734,19.374,14.156,14.690,7.098,9.402,11.112,9.441,9.089,13.598,13.420,17.312,20.342,26.998,41.397,58.654,73.038,98.790,81.705,95.547,125.552,143.573,153.761,164.448,131.661,114.764,139.835,114.189,94.671,66.521,84.375,142.403,114.336,117.159,6.561470,16.383583,23.935119
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,548,Vanuatu,0.038,0.041,0.055,0.067,0.066,0.080,0.078,0.081,0.099,0.130,0.124,0.108,0.107,0.115,0.139,0.133,0.129,0.137,0.161,0.158,0.171,0.204,0.213,0.219,0.240,0.273,0.283,0.285,0.260,0.265,0.265,0.255,0.264,0.314,0.365,0.395,0.439,0.526,0.591,0.593,0.671,0.770,0.748,0.758,0.774,0.760,0.804,0.880,0.915,0.937,0.909,0.982,1.031,1.090,1.092,5.068552,8.806452,7.903286
175,862,Venezuela (Bolivarian Republic of),13.864,15.227,16.744,20.000,30.465,32.093,36.744,42.326,46.047,56.512,69.070,77.674,79.302,79.070,58.005,60.000,58.515,46.483,58.276,41.451,47.045,51.720,58.465,58.101,57.164,74.892,68.257,85.837,91.337,97.974,117.147,122.912,92.889,83.529,112.451,145.514,183.477,230.364,315.600,329.419,393.806,316.483,381.286,371.338,363.090,343.661,287.807,247.051,203.127,149.256,105.889,111.775,129.303,139.459,150.494,1.785764,2.178862,18.280182
176,704,Viet Nam,2.775,3.024,3.237,3.350,3.605,3.896,4.541,5.413,6.532,7.140,2.396,1.885,2.190,3.289,5.069,4.758,5.017,5.272,5.736,6.241,6.417,7.578,9.867,13.181,16.281,20.736,24.658,26.844,27.210,28.684,31.173,32.685,35.064,39.553,49.494,57.633,69.618,85.174,114.402,128.331,147.201,172.595,195.591,213.709,233.451,239.258,257.096,281.354,310.106,334.365,346.616,366.475,413.445,433.858,476.388,12.781546,198.826377,13.221009
177,894,Zambia,1.544,1.574,1.852,2.350,2.895,2.658,2.814,2.767,3.098,3.827,4.315,4.016,4.275,3.992,3.194,2.772,2.105,2.108,3.471,3.956,3.795,3.377,3.307,3.274,3.657,3.807,3.597,4.303,3.538,3.404,3.601,4.094,4.194,4.902,6.221,8.329,12.762,14.060,17.914,15.332,20.264,23.455,25.502,28.042,27.145,21.245,20.965,25.874,26.311,23.309,18.138,22.096,29.164,27.578,25.303,4.101956,5.863963,19.438674
178,716,Zimbabwe,2.337,2.702,3.336,4.104,4.938,5.421,5.357,5.411,5.413,6.422,8.257,9.935,10.590,9.628,7.877,8.720,9.616,10.426,12.086,12.781,13.560,12.652,10.434,10.135,10.656,11.063,13.466,13.854,9.706,9.225,8.721,8.659,8.215,7.747,7.416,7.189,7.049,6.958,6.348,9.666,12.042,14.102,17.115,19.091,19.496,22.300,25.640,30.720,36.814,39.295,33.747,36.001,38.966,44.476,45.719,3.966303,5.536999,14.014585

In [44]:
df_clean.to_excel("C:\Projects\DAP\gdp-growth-analysis\data\data_gdp_final.xlsx", index=False)

Equatorial Guinea records the highest GDP growth volatility, followed by Iraq and Angola. This suggests that these economies experienced the most unstable growth paths over the analysis period.

### Total Growth from 1980 to 2024

In [43]:
compute_growth_between(df_clean, 1980, 2024)

0        402.004393
1       1162.231559
2        531.856480
3        615.044248
4       1538.358272
           ...
174      780.645161
175      117.886202
176    19782.637730
177      486.396292
178      453.699891
Length: 179, dtype: float64

## Hypothesis Testing

This section adds statistical validation to the descriptive analysis. The tests below examine whether key visual patterns in the notebook are supported by statistically significant evidence.

In [115]:
# ---------------------------------------------
# Statistical testing imports
# ---------------------------------------------
# Import statistical testing functions from scipy
from scipy.stats import ttest_1samp, pearsonr, ttest_ind

# Define the significance level used across all tests
alpha = 0.05

print(f"Significance level (alpha): {alpha}")

Significance level (alpha): 0.05

### Test 1: Was Average GDP Growth in 2020 Significantly Different from 0?

- **Null Hypothesis (H0):** The mean GDP growth rate in 2020 is equal to 0.
- **Alternative Hypothesis (H1):** The mean GDP growth rate in 2020 is different from 0.

A one-sample t-test is used because the sample mean is evaluated against a benchmark value of 0.

In [116]:
# Calculate country-level GDP growth rates for the year 2020
growth_2020 = compute_growth(df_clean, 2020).dropna()

# Perform a one-sample t-test against a population mean of 0
t_stat_2020, p_value_2020 = ttest_1samp(growth_2020, popmean=0)

# Print test statistics
print("Test 1: 2020 GDP Growth vs 0")
print(f"Sample mean growth (2020): {growth_2020.mean():.4f}%")
print(f"T-statistic: {t_stat_2020:.4f}")
print(f"P-value: {p_value_2020:.6f}")

# Interpret the result at alpha = 0.05
if p_value_2020 < alpha:
    print("Reject the null hypothesis at alpha = 0.05.")
    print("The mean GDP growth rate in 2020 is significantly different from 0.")
else:
    print("Accept the null hypothesis at alpha = 0.05.")
    print("The mean GDP growth rate in 2020 is not significantly different from 0.")

Test 1: 2020 GDP Growth vs 0
Sample mean growth (2020): -6.2235%
T-statistic: -7.7372
P-value: 0.000000
Reject the null hypothesis at alpha = 0.05.
The mean GDP growth rate in 2020 is significantly different from 0.

### Test 2: Was Average Post-COVID Recovery Growth in 2021-2024 Greater than 0?

- **Null Hypothesis (H0):** The mean post-COVID recovery growth rate is equal to 0.
- **Alternative Hypothesis (H1):** The mean post-COVID recovery growth rate is greater than 0.

Country-level recovery growth is averaged across 2021-2024 before applying the statistical test.

In [117]:
# Define the recovery years after the 2020 shock
recovery_years = [2021, 2022, 2023, 2024]

# Compute annual recovery growth for each year and store them as columns
recovery_growth_df = pd.DataFrame({
    year: compute_growth(df_clean, year) for year in recovery_years
})

# Average recovery growth across 2021-2024 for each country
avg_recovery_growth = recovery_growth_df.mean(axis=1).dropna()

# Perform a one-sample t-test against a population mean of 0
t_stat_recovery, p_value_recovery_two_tailed = ttest_1samp(avg_recovery_growth, popmean=0)

# Convert the two-tailed p-value into a one-tailed p-value for the hypothesis: mean > 0
if t_stat_recovery > 0:
    p_value_recovery = p_value_recovery_two_tailed / 2
else:
    p_value_recovery = 1 - (p_value_recovery_two_tailed / 2)

# Print test statistics
print("Test 2: Post-COVID Recovery Growth (2021-2024) > 0")
print(f"Sample mean recovery growth: {avg_recovery_growth.mean():.4f}%")
print(f"T-statistic: {t_stat_recovery:.4f}")
print(f"One-tailed P-value: {p_value_recovery:.6f}")

# Interpret the result at alpha = 0.05
if p_value_recovery < alpha:
    print("Reject the null hypothesis at alpha = 0.05.")
    print("The mean post-COVID recovery growth is significantly greater than 0.")
else:
    print("Accept the null hypothesis at alpha = 0.05.")
    print("The mean post-COVID recovery growth is not significantly greater than 0.")

Test 2: Post-COVID Recovery Growth (2021-2024) > 0
Sample mean recovery growth: 8.1257%
T-statistic: 19.0851
One-tailed P-value: 0.000000
Reject the null hypothesis at alpha = 0.05.
The mean post-COVID recovery growth is significantly greater than 0.

### Test 3: Is Long-Run GDP Growth Associated with Growth Volatility?

- **Null Hypothesis (H0):** There is no linear relationship between `CAGR_%` and `Growth_Volatility`.
- **Alternative Hypothesis (H1):** There is a statistically significant linear relationship between the two variables.

A Pearson correlation test is used because both variables are continuous.

In [118]:
# Select the two variables needed for the correlation test and remove missing values
corr_data = df_clean[["CAGR", "Growth_Volatility"]].dropna()

# Perform Pearson correlation test
corr_coef, p_value_corr = pearsonr(corr_data["CAGR"], corr_data["Growth_Volatility"])

# Print test statistics
print("Test 3: CAGR vs Growth Volatility")
print(f"Pearson correlation coefficient: {corr_coef:.4f}")
print(f"P-value: {p_value_corr:.6f}")

# Interpret the result at alpha = 0.05
if p_value_corr < alpha:
    print("Reject the null hypothesis at alpha = 0.05.")
    print("There is a statistically significant relationship between long-run growth and volatility.")
else:
    print("Accept the null hypothesis at alpha = 0.05.")
    print("There is no statistically significant relationship between long-run growth and volatility.")

Test 3: CAGR vs Growth Volatility
Pearson correlation coefficient: -0.1476
P-value: 0.048652
Reject the null hypothesis at alpha = 0.05.
There is a statistically significant relationship between long-run growth and volatility.

### Test 4: Are the Largest Economies More Stable Than the Rest of the World?

- **Null Hypothesis (H0):** The mean growth volatility of the top 10 economies is equal to that of all other countries.
- **Alternative Hypothesis (H1):** The mean growth volatility of the top 10 economies is different from that of all other countries.

Welch's two-sample t-test is used because it compares two independent groups without assuming equal variance.

In [119]:
# Identify the top 10 economies based on 2024 GDP
top_10_countries = df_clean.sort_values(by=2024, ascending=False).head(10)["Country"]

# Split the dataset into top 10 economies and the rest of the countries
top_10_volatility = df_clean[df_clean["Country"].isin(top_10_countries)]["Growth_Volatility"].dropna()
rest_volatility = df_clean[~df_clean["Country"].isin(top_10_countries)]["Growth_Volatility"].dropna()

# Perform Welch's independent two-sample t-test
t_stat_vol, p_value_vol = ttest_ind(top_10_volatility, rest_volatility, equal_var=False)

# Print test statistics
print("Test 4: Top 10 Economies vs Rest of World Volatility")
print(f"Mean volatility (Top 10 economies): {top_10_volatility.mean():.4f}")
print(f"Mean volatility (Rest of world): {rest_volatility.mean():.4f}")
print(f"T-statistic: {t_stat_vol:.4f}")
print(f"P-value: {p_value_vol:.6f}")

# Interpret the result at alpha = 0.05
if p_value_vol < alpha:
    print("Reject the null hypothesis at alpha = 0.05.")
    print("The largest economies have a significantly different average volatility from the rest of the world.")
else:
    print("Accept the null hypothesis at alpha = 0.05.")
    print("There is no statistically significant difference in volatility between the largest economies and the rest of the world.")

Test 4: Top 10 Economies vs Rest of World Volatility
Mean volatility (Top 10 economies): 9.8964
Mean volatility (Rest of world): 12.2440
T-statistic: -1.9311
P-value: 0.081058
Accept the null hypothesis at alpha = 0.05.
There is no statistically significant difference in volatility between the largest economies and the rest of the world.

### Interpretation Notes

These tests strengthen the notebook by moving from descriptive observation to analytical validation:

- Test 1 evaluates the statistical visibility of the 2020 shock.
- Test 2 examines whether the post-pandemic recovery was meaningfully positive.
- Test 3 assesses the empirical basis of the growth-versus-volatility pattern.
- Test 4 checks whether economic size is associated with lower instability.

## Visualization and Descriptive Interpretation

The following visualizations summarize GDP trends, concentration, volatility, recovery dynamics, and cross-country comparisons derived from the engineered features.

In [120]:
# ---------------------------------------------
# Visualization library imports
# ---------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

### GDP Trend Comparison: India, United States, and China (1980-2024)

In [121]:
import plotly.graph_objects as go

countries = ["India", "United States", "China"]

fig = go.Figure()

for country in countries:
    data = df_clean[df_clean["Country"] == country][analysis_years].values.flatten()
    
    fig.add_trace(go.Scatter(
        x=analysis_years,
        y=data,
        mode='lines',
        name=country
    ))

fig.update_layout(
    title=dict(
        text="GDP Trend Comparison (1980–2024)",
        x=0.5
    ),
    xaxis_title="Year",
    yaxis_title="GDP (Current US$)",
    width=1000,
    height=600,
    template="plotly_white"
)

fig.show()

### Key Interpretation

From 1980 to 2024, the United States remains the largest economy throughout the period, China shows the sharpest acceleration after 2000, and India demonstrates sustained long-run growth from a lower base.

### Top 10 Countries by Growth Volatility (1980-2024)

In [122]:
import plotly.graph_objects as go

top10 = df_clean.sort_values("Growth_Volatility", ascending=False).head(10)

fig = go.Figure()

fig.add_trace(go.Bar(
    x=top10["Growth_Volatility"],
    y=top10["Country"],
    orientation='h'
))

fig.update_layout(
    title=dict(
        text="Top 10 Countries by Growth Volatility (1980–2024)",
        x=0.5
    ),
    xaxis_title="Growth_Volatility",
    yaxis_title="Country",
    width=800,
    height=600,
    template="plotly_white"
)

# Match seaborn ordering (highest at top)
fig.update_yaxes(autorange="reversed")

fig.show()

### Key Interpretation

Growth volatility is concentrated in politically unstable, conflict-affected, and resource-dependent economies, indicating higher macroeconomic uncertainty and less predictable development paths.

### Largest and Smallest Economies in 2024

In [123]:
latest_year = 2024

# Sort countries by GDP
top_10 = df_clean.sort_values(by=latest_year, ascending=False).head(10)
bottom_10 = df_clean.sort_values(by=latest_year, ascending=True).head(10)

In [124]:
print("Top 10 cuntries by GDP: ")
top_10

Top 10 cuntries by GDP:

,CountryID,Country,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,CAGR,GDP_Multiplier,Growth_Volatility
172,840,United States,1073.303,1164.850,1279.110,1425.376,1545.243,1684.904,1873.412,2081.826,2351.599,2627.333,2857.307,3207.041,3343.789,3634.038,4037.613,4338.979,4579.631,4855.215,5236.438,5641.580,5963.144,6158.129,6520.327,6858.559,7287.236,7639.749,8073.122,8577.552,9062.817,9631.172,10250.952,10581.929,10929.108,11456.450,12217.196,13039.197,13815.583,14474.228,14769.862,14478.067,15048.971,15599.732,16253.970,16880.683,17608.138,18295.019,18804.913,19612.102,20656.516,21540.000,21375.300,23725.600,26054.600,27811.500,29298.000,5.432516,10.253711,2.674412
36,156,China,92.603,99.801,113.689,138.543,144.189,163.429,153.939,174.936,218.503,263.708,306.169,289.568,283.925,304.752,313.723,309.839,300.516,327.090,407.845,456.287,394.566,413.376,493.137,619.116,564.322,734.485,863.749,961.601,1029.061,1094.004,1211.331,1339.401,1470.557,1660.280,1955.347,2317.551,2791.498,3604.056,4667.346,5189.577,6192.565,7671.757,8673.665,9743.124,10674.533,11280.815,11456.024,12537.559,14147.765,14560.167,14996.414,18201.698,18316.765,18270.356,18743.802,9.802261,61.220444,10.310182
64,276,Germany,216.626,250.901,300.895,399.840,446.936,492.423,521.645,602.691,743.187,884.538,953.815,803.391,779.424,773.531,727.764,735.206,1050.129,1302.944,1406.299,1404.166,1778.138,1875.770,2141.488,2078.882,2215.225,2592.880,2506.646,2218.769,2247.751,2213.873,1966.981,1966.381,2102.351,2534.716,2852.318,2893.393,3046.309,3484.057,3808.786,3479.801,3468.154,3824.829,3597.897,3808.086,3965.801,3423.568,3537.784,3763.092,4052.008,3957.208,3940.143,4348.297,4163.596,4525.704,4659.929,3.670970,4.885569,11.074525
85,392,Japan,217.224,245.364,324.934,441.461,490.036,532.861,598.884,737.069,1035.612,1077.910,1129.377,1245.221,1158.732,1270.860,1345.825,1427.020,2120.083,2580.748,3125.725,3109.455,3185.905,3648.067,3980.702,4536.941,4998.797,5545.565,4923.393,4492.450,4098.363,4635.982,4968.359,4374.710,4182.845,4519.563,4893.135,4831.467,4601.663,4579.750,5106.679,5289.494,5759.072,6233.147,6272.363,5212.328,4896.994,4444.931,5003.678,4930.837,5040.881,5117.994,5054.068,5039.148,4262.463,4213.167,4026.211,2.931135,3.564984,11.530937
77,356,India,62.422,66.898,72.744,86.851,97.978,101.735,102.464,119.039,137.524,152.062,187.033,199.544,204.391,222.870,221.946,230.043,252.454,279.184,308.515,304.014,329.139,291.200,293.693,287.274,327.525,371.783,393.647,425.545,429.550,461.791,476.148,490.659,512.775,599.470,703.129,823.612,939.066,1184.724,1267.470,1315.230,1669.620,1871.918,1860.877,1917.054,2042.939,2146.759,2290.587,2624.329,2763.535,2854.799,2679.381,3192.375,3420.984,3646.879,3952.244,7.179553,21.131266,7.553496
171,826,United Kingdom,130.682,148.107,169.969,192.552,206.152,241.735,232.610,263.079,335.880,439.012,564.954,540.721,515.007,489.600,461.483,489.256,601.455,745.130,910.171,926.926,1093.214,1142.766,1179.713,1061.458,1140.443,1349.162,1425.380,1569.225,1660.757,1693.577,1671.520,1656.278,1790.474,2061.320,2429.864,2551.370,2719.625,3104.876,2945.435,2429.285,2496.741,2675.590,2719.716,2796.908,3085.362,2945.580,2706.808,2699.208,2897.222,2875.710,2724.001,3194.559,3181.244,3420.797,3685.881,4.354698,6.524214,9.305570
60,250,France,146.922,164.247,201.612,262.334,283.092,356.796,368.490,406.741,501.712,608.236,694.546,609.184,578.146,553.376,525.046,547.225,764.964,926.294,1010.794,1016.694,1257.609,1258.910,1389.599,1314.454,1385.817,1595.122,1598.979,1449.396,1496.947,1486.916,1360.959,1370.377,1492.428,1835.096,2109.792,2192.146,2317.862,2655.817,2926.803,2700.076,2646.230,2870.409,2683.007,2816.078,2861.236,2442.483,2470.408,2588.868,2781.576,2722.794,2647.926,2966.434,2794.788,3056.251,3160.443,3.503637,4.550372,10.519788
83,380,Italy,113.662,124.964,145.592,175.901,200.040,228.242,225.253,258.181,315.786,394.581,478.337,431.703,428.249,444.052,438.900,453.240,641.830,807.613,893.618,930.766,1184.007,1249.047,1323.237,1067.372,1101.805,1177.406,1314.833,1245.022,1272.763,1255.005,1149.661,1172.041,1281.746,1582.930,1812.809,1864.982,1958.564,2222.524,2417.508,2209.484,2144.936,2306.974,2097.929,2153.226,2173.256,1845.428,1887.111,1970.721,2099.435,2019.607,1907.481,2179.208,2104.068,2316.728,2380.825,3.714806,4.977296,11.170804
31,124,Canada,89.208,100.677,114.591,132.954,161.731,174.926,208.905,214.023,220.991,245.520,276.064,307.246,314.639,341.863,356.728,366.184,379.015,433.140,509.380,567.225,596.089,612.514,594.376,579.059,579.913,605.941,630.598,655.010,634.004,678.417,744.631,738.968,760.149,895.599,1026.473,1173.505,1319.356,1468.896,1552.864,1376.509,1617.345,1793.327,1828.362,1846.595,1805.751,1556.508,1527.996,1649.266,1725.300,1743.725,1655.685,2022.382,2200.567,2196.594,2270.076,4.904991,8.223006,7.585305
22,76,Brazil,35.381,39.518,50.863,72.012,92.323,108.563,128.346,149.375,169.602,186.976,176.174,224.382,245.734,173.009,176.307,188.205,226.408,248.287,277.346,377.263,408.823,379.159,362.039,404.957,575.828,769.333,850.426,883.206,863.711,599.642,655.448,559.984,509.795,558.234,669.289,891.634,1107.627,1397.114,1695.855,1666.996,2208.838,2616.157,2465.228,2472.819,2456.044,1802.212,1795.693,2063.515,1916.934,1873.288,1476.107,1670.647,1951.924,2191.132,2185.822,5.890306,12.407177,17.238676

In [125]:
print("Bottom 10 countries by GDP:")
bottom_10

Bottom 10 countries by GDP:

,CountryID,Country,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,CAGR,GDP_Multiplier,Growth_Volatility
167,798,Tuvalu,0.003,0.003,0.003,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.005,0.004,0.004,0.004,0.004,0.004,0.005,0.008,0.008,0.010,0.010,0.011,0.010,0.011,0.012,0.012,0.013,0.013,0.014,0.014,0.013,0.016,0.018,0.022,0.022,0.023,0.027,0.030,0.027,0.031,0.038,0.037,0.038,0.038,0.036,0.041,0.045,0.048,0.054,0.052,0.061,0.054,0.051,0.056,6.181380,14.000000,13.512568
110,500,Montserrat,0.008,0.009,0.010,0.012,0.013,0.014,0.013,0.014,0.016,0.019,0.028,0.033,0.037,0.039,0.042,0.044,0.046,0.050,0.057,0.064,0.075,0.064,0.067,0.067,0.073,0.069,0.056,0.045,0.041,0.039,0.038,0.038,0.042,0.043,0.046,0.051,0.053,0.055,0.059,0.060,0.056,0.062,0.063,0.060,0.059,0.062,0.063,0.060,0.065,0.068,0.067,0.069,0.072,0.076,0.081,2.443570,2.892857,8.314103
115,520,Nauru,0.015,0.017,0.019,0.026,0.031,0.034,0.034,0.034,0.037,0.038,0.042,0.045,0.042,0.041,0.040,0.033,0.033,0.037,0.043,0.046,0.049,0.046,0.043,0.037,0.037,0.035,0.034,0.031,0.024,0.025,0.022,0.019,0.019,0.024,0.028,0.026,0.025,0.023,0.042,0.054,0.059,0.088,0.121,0.118,0.133,0.104,0.115,0.128,0.146,0.141,0.148,0.204,0.168,0.173,0.187,3.452439,4.452381,19.671400
103,584,Marshall Islands,0.008,0.009,0.010,0.012,0.015,0.017,0.018,0.020,0.022,0.026,0.027,0.031,0.035,0.042,0.046,0.044,0.057,0.064,0.071,0.073,0.079,0.083,0.093,0.102,0.112,0.125,0.116,0.110,0.112,0.113,0.115,0.122,0.132,0.131,0.133,0.138,0.143,0.150,0.146,0.151,0.160,0.172,0.180,0.185,0.185,0.183,0.201,0.213,0.219,0.232,0.242,0.260,0.254,0.260,0.281,5.468173,10.407407,6.660770
126,585,Palau,0.009,0.010,0.011,0.012,0.014,0.015,0.016,0.018,0.020,0.022,0.024,0.026,0.029,0.032,0.036,0.041,0.047,0.053,0.061,0.069,0.079,0.087,0.093,0.086,0.091,0.110,0.132,0.143,0.148,0.143,0.148,0.158,0.162,0.158,0.173,0.185,0.189,0.195,0.198,0.184,0.183,0.194,0.213,0.224,0.243,0.280,0.299,0.286,0.285,0.282,0.259,0.236,0.256,0.282,0.310,5.987200,12.916667,7.353766
88,296,Kiribati,0.020,0.020,0.023,0.037,0.057,0.056,0.039,0.035,0.038,0.034,0.033,0.035,0.033,0.031,0.034,0.026,0.026,0.030,0.038,0.038,0.037,0.041,0.061,0.059,0.067,0.069,0.081,0.080,0.075,0.077,0.075,0.065,0.075,0.096,0.104,0.114,0.112,0.138,0.147,0.140,0.165,0.196,0.207,0.202,0.200,0.192,0.206,0.223,0.234,0.217,0.221,0.286,0.271,0.291,0.343,5.465069,10.393939,12.966960
42,184,Cook Islands,0.011,0.011,0.012,0.015,0.018,0.017,0.016,0.019,0.022,0.025,0.028,0.029,0.029,0.028,0.029,0.031,0.040,0.050,0.064,0.065,0.073,0.079,0.082,0.091,0.109,0.116,0.117,0.107,0.093,0.100,0.100,0.107,0.125,0.174,0.206,0.214,0.224,0.251,0.255,0.243,0.266,0.300,0.325,0.316,0.351,0.320,0.319,0.357,0.395,0.391,0.268,0.256,0.289,0.366,0.414,6.313233,14.785714,12.305054
5,660,Anguilla,0.004,0.005,0.005,0.006,0.007,0.007,0.007,0.008,0.009,0.011,0.012,0.014,0.016,0.019,0.022,0.027,0.035,0.044,0.055,0.068,0.076,0.078,0.084,0.092,0.103,0.104,0.110,0.123,0.139,0.148,0.151,0.155,0.155,0.169,0.200,0.227,0.282,0.353,0.354,0.281,0.265,0.290,0.286,0.286,0.315,0.329,0.317,0.278,0.317,0.380,0.261,0.305,0.397,0.429,0.456,8.618593,38.000000,12.576084
107,583,Micronesia (FS of),0.021,0.023,0.027,0.037,0.049,0.049,0.050,0.050,0.057,0.064,0.068,0.081,0.085,0.089,0.090,0.108,0.119,0.124,0.137,0.144,0.158,0.176,0.189,0.207,0.214,0.222,0.219,0.207,0.220,0.221,0.233,0.240,0.241,0.245,0.241,0.251,0.253,0.257,0.263,0.280,0.297,0.311,0.327,0.317,0.319,0.316,0.332,0.367,0.392,0.394,0.372,0.390,0.430,0.444,0.471,4.496693,6.926471,5.271821
162,776,Tonga,0.017,0.019,0.023,0.034,0.046,0.043,0.039,0.045,0.054,0.058,0.079,0.082,0.085,0.086,0.086,0.073,0.088,0.105,0.145,0.151,0.162,0.195,0.193,0.190,0.196,0.209,0.222,0.215,0.191,0.197,0.191,0.167,0.181,0.207,0.239,0.261,0.290,0.303,0.337,0.320,0.371,0.439,0.421,0.442,0.433,0.404,0.421,0.461,0.484,0.502,0.509,0.522,0.543,0.591,0.648,4.899047,8.202532,9.725275

In [126]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Reverse top_10 (same as matplotlib)
top_10 = top_10.iloc[::-1]

# Create subplots
fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=("Top 10 Economies (2024)", "Bottom 10 Economies (2024)"),
    horizontal_spacing=0.08
)

# ---------------- LEFT: Top 10 (Right → Left bars)
fig.add_trace(
    go.Bar(
        x=top_10[latest_year],
        y=top_10["Country"],
        orientation='h'
    ),
    row=1, col=1
)

# Invert x-axis (right → left effect)
fig.update_xaxes(autorange="reversed", title_text="GDP (Billions)", row=1, col=1)

# ---------------- RIGHT: Bottom 10 (Normal)
fig.add_trace(
    go.Bar(
        x=bottom_10[latest_year],
        y=bottom_10["Country"],
        orientation='h'
    ),
    row=1, col=2
)

fig.update_xaxes(title_text="GDP (Billions)", row=1, col=2)

# Move y-axis to right side for second subplot
fig.update_yaxes(side="right", row=1, col=2)

# Layout
fig.update_layout(
    width=1400,
    height=600,
    template="plotly_white",
    showlegend=False
)

fig.show()

### Key Interpretation

Global GDP remains highly concentrated. The largest economies operate at a vastly different scale from the smallest nations, highlighting a persistent imbalance in economic size across countries.

### Long-Term Growth Leaders

In [127]:
start_year = 1980
end_year = 2024

# Compute CAGR using your function
df_clean.rename(columns={"CAGR": "CAGR_%"}, inplace=True) # renaming the CAGR column to CAGR_%
df_clean["CAGR_%"] = compute_cagr(df_clean, start_year, end_year)

df_clean.head()

,CountryID,Country,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,CAGR_%,GDP_Multiplier,Growth_Volatility
0,4,Afghanistan,1.749,1.831,1.596,1.733,2.156,2.367,2.556,2.953,3.300,3.698,3.642,3.479,3.439,3.399,3.360,3.322,3.321,2.887,2.664,3.342,3.622,3.340,3.475,2.664,2.115,3.236,3.124,3.016,2.912,2.720,3.532,3.621,4.285,4.899,5.504,6.475,7.293,9.999,10.296,11.932,15.145,17.923,19.794,19.904,19.500,18.700,18.224,19.034,18.856,19.372,19.983,15.161,14.175,16.340,18.283,3.734966,5.020044,15.133276
1,8,Albania,2.266,2.331,2.398,2.467,2.537,2.610,2.686,2.761,2.842,2.372,2.142,2.215,2.280,2.305,2.276,2.324,2.397,2.378,2.460,2.941,2.146,1.597,1.516,1.700,1.881,2.905,3.234,2.259,2.609,3.294,3.592,4.064,4.523,5.750,7.399,8.257,9.151,11.117,13.259,12.336,12.087,12.974,12.247,12.797,13.296,11.470,11.989,13.258,15.380,15.585,15.241,18.032,19.017,23.491,27.037,5.931687,12.622316,15.094975
2,12,Algeria,5.155,5.364,7.176,9.230,13.260,15.556,17.750,20.991,26.374,33.201,42.252,44.265,45.095,48.702,52.828,57.866,62.923,64.334,58.655,55.344,61.751,46.565,49.106,50.847,42.331,41.971,46.836,48.806,49.566,50.800,58.101,59.413,61.516,73.482,91.914,107.047,123.084,142.483,180.384,150.317,177.785,218.332,227.144,229.701,238.943,187.494,180.764,189.881,194.554,193.460,164.873,186.232,225.638,247.626,266.972,4.278764,6.318565,11.745418
3,20,Andorra,0.099,0.113,0.144,0.191,0.236,0.279,0.288,0.321,0.390,0.521,0.565,0.492,0.476,0.415,0.418,0.439,0.610,0.773,0.913,1.007,1.302,1.401,1.531,1.274,1.288,1.491,1.549,1.494,1.534,1.569,1.433,1.548,1.764,2.367,2.900,3.161,3.459,3.958,4.102,3.689,3.450,3.629,3.189,3.194,3.272,2.790,2.897,3.000,3.218,3.155,2.891,3.325,3.381,3.785,4.040,4.572299,7.150442,12.653118
4,24,Angola,3.807,4.007,4.102,5.016,5.627,4.147,3.981,4.344,4.845,5.380,7.151,6.693,6.693,6.975,7.394,9.109,8.549,9.844,10.716,12.574,14.006,16.734,19.374,14.156,14.690,7.098,9.402,11.112,9.441,9.089,13.598,13.420,17.312,20.342,26.998,41.397,58.654,73.038,98.790,81.705,95.547,125.552,143.573,153.761,164.448,131.661,114.764,139.835,114.189,94.671,66.521,84.375,142.403,114.336,117.159,6.561470,16.383583,23.935119

In [128]:
df_growth = df_clean[df_clean[start_year] > 1].copy() # accessing the countries with starting GDP > 1 for removing bias in growth

In [129]:
top_growth = df_growth.sort_values(by="CAGR_%", ascending=False).head(10)
top_growth = top_growth.iloc[::-1]

In [130]:
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Bar(
    x=top_growth["CAGR_%"],
    y=top_growth["Country"],
    orientation='h',
    text=[f"{v:.2f}%" for v in top_growth["CAGR_%"]],
    textposition='outside'
))

fig.update_layout(
    title=dict(
        text="Top 10 Fastest Growing Economies (1980–2024)",
        x=0.5
    ),
    xaxis_title="CAGR (%)",
    yaxis_title="Countries",
    width=1000,
    height=600,
    template="plotly_white"
)

# Match matplotlib ordering (top to bottom)
fig.update_yaxes(autorange="reversed")

fig.show()

### Key Interpretation

Asian economies dominate the long-run growth ranking, with Vietnam standing out as a particularly strong performer. Most high-growth countries cluster within a relatively narrow long-term CAGR range.

### Decade-Wise Growth Performance

In [131]:
import plotly.graph_objects as go

# Decade-wise Average Annual Growth Rate 
decades = {
    "1980s": [y for y in range(1980, 1990)],
    "1990s": [y for y in range(1990, 2000)],
    "2000s": [y for y in range(2000, 2010)],
    "2010s": [y for y in range(2010, 2020)],
    "2020s": [y for y in range(2020, 2025)]
}

decade_growth = pd.DataFrame()
decade_growth["Country"] = df_clean["Country"]

for label, years in decades.items():
    growth_rates = []
    for i in range(1, len(years)):
        y_curr, y_prev = years[i], years[i-1]
        rate = ((df_clean[y_curr] - df_clean[y_prev]) / df_clean[y_prev]) * 100
        growth_rates.append(rate)
    
    decade_growth[label] = pd.concat(growth_rates, axis=1).mean(axis=1)

# Heatmap data
top_10_names = df_clean.sort_values(2024, ascending=False).head(10)["Country"]
heatmap_data = decade_growth[decade_growth["Country"].isin(top_10_names)].set_index("Country")

# Plotly Heatmap
fig = go.Figure(data=go.Heatmap(
    z=heatmap_data.values,
    x=heatmap_data.columns,
    y=heatmap_data.index,
    colorscale='RdYlGn',
    zmid=0,
    text=[[f"{val:.2f}" for val in row] for row in heatmap_data.values],
    texttemplate="%{text}",
    colorbar=dict(title="")
))

fig.update_layout(
    title=dict(
        text="Average Annual Growth Rate (%) by Decade (Top 10 Economies)",
        x=0.5
    ),
    width=1200,
    height=600,
    template="plotly_white"
)

fig.show()

### Insight 
Geopolitical Growth Shift: The heatmap captures a fundamental shift from Japan’s 1980s dominance to an emerging market explosion in the 2000s, where China and India led the world with peak annual growth exceeding 12%.

Maturity and Cooling: Western economies show a transition from vibrant green to cooler tones, illustrating the natural deceleration that occurs as nations reach high-income status and face structural aging.

### Global GDP Concentration

In [132]:
import plotly.graph_objects as go

# Global GDP Share Analysis
years_to_check = [1980, 2000, 2024]
share_data = []

for year in years_to_check:
    world_gdp = df_clean[year].sum()
    top_10_sum = df_clean.sort_values(year, ascending=False).head(10)[year].sum()
    share_data.append({
        "Year": year,
        "Top 10 Share": (top_10_sum / world_gdp) * 100,
        "Rest of World": ((world_gdp - top_10_sum) / world_gdp) * 100
    })

df_share = pd.DataFrame(share_data)

# Plotly Stacked Bar Chart
fig = go.Figure()

fig.add_trace(go.Bar(
    x=df_share["Year"],
    y=df_share["Top 10 Share"],
    name="Top 10 Share",
    marker=dict(color='#1f77b4')
))

fig.add_trace(go.Bar(
    x=df_share["Year"],
    y=df_share["Rest of World"],
    name="Rest of World",
    marker=dict(color='#aec7e8')
))

fig.update_layout(
    title=dict(
        text="Concentration of Global GDP: Top 10 vs. Rest of the World",
        x=0.5
    ),
    xaxis_title="Year",
    yaxis_title="Percentage of Global GDP (%)",
    barmode='stack',
    width=1000,
    height=600,
    template="plotly_white",
    legend=dict(
        x=1.05,
        y=1
    )
)

fig.update_xaxes(type='category', tickangle=0)

fig.show()

### Insight
Persistent Market Dominance: The Top 10 economies consistently control a vast majority of global wealth, maintaining a stable share of approximately 65-70% of world GDP over the last four decades.

High Entry Barrier: Despite the growth of emerging markets, the "Rest of the World" share has not significantly expanded, indicating that economic power remains highly concentrated within a small cluster of dominant nations

### Risk vs. Reward: Growth and Volatility

In [133]:
fig_bubble = px.scatter(
    df_clean, 
    x="CAGR_%", 
    
    y="Growth_Volatility",
    size=2024, 
    color="CAGR_%",
    hover_name="Country",
    size_max=60,
    title="<b>Economic Risk vs. Reward: Growth vs. Volatility (1980–2024)</b>",
    labels={
        "CAGR_%": "Compound Annual Growth Rate (%)", 
        "Growth_Volatility": "Growth Volatility (Std Dev)"
    },
    color_continuous_scale=px.colors.sequential.Viridis,
    template="plotly_dark" # Using dark theme for high-contrast professional look
)

# Add reference lines for Global Averages
fig_bubble.add_hline(y=df_clean['Growth_Volatility'].mean(), line_dash="dash", line_color="red", 
                     annotation_text="Avg Volatility")
fig_bubble.add_vline(x=df_clean['CAGR_%'].mean(), line_dash="dash", line_color="yellow", 
                     annotation_text="Avg Growth")

fig_bubble.show()

### Insight
The Stability Frontier: A clear correlation exists between economic scale and stability; larger economies (bigger bubbles) tend to cluster in the "Low Volatility" zone, prioritizing predictable growth over high-risk expansion.

Developing Market Volatility: Smaller, high-growth nations are positioned higher on the Y-axis, highlighting that the "reward" of rapid CAGR is almost always accompanied by the "risk" of significant year-over-year fluctuations.

### GDP Component Breakdown for an Economy

This example uses India to illustrate how major macroeconomic components evolve over time within a single national economy.

In [134]:
import plotly.graph_objects as go

# Economic Composition Analysis (Example: India)
target_country = "India"
components = [
    "Final consumption expenditure",
    "Gross capital formation",
    "Exports of goods and services",
    "Imports of goods and services"
]

# Extract data from original dataframe
df_comp = df_original[(df_original["Country"] == target_country) & 
                     (df_original["IndicatorName"].isin(components))].copy()

# Melt and prepare for plotting
df_comp_years = df_comp.set_index("IndicatorName")[analysis_years].T / 1e9  # Convert to Billions

fig = go.Figure()

for col in df_comp_years.columns:
    fig.add_trace(go.Scatter(
        x=df_comp_years.index,
        y=df_comp_years[col],
        mode='lines+markers',
        name=col,
        marker=dict(size=4)
    ))

fig.update_layout(
    title=dict(
        text=f"Economic Drivers of {target_country} (1980–2024)",
        x=0.5
    ),
    xaxis_title="Year",
    yaxis_title="Value (Billions Current US$)",
    width=1200,
    height=600,
    template="plotly_white"
)

# Grid similar to matplotlib
fig.update_xaxes(showgrid=True, gridcolor='rgba(0,0,0,0.2)')
fig.update_yaxes(showgrid=True, gridcolor='rgba(0,0,0,0.2)')

fig.show()

### Insights
Consumption-Led Growth: The visualization reveals that final consumption expenditure remains the primary driver of the economy, consistently maintaining the largest share of total value over the decades.

Trade Dynamics & Investment: The parallel rise in exports, imports, and capital formation highlights a transition toward a more globally integrated and investment-heavy economy, particularly accelerating after the early 2000s.

### The COVID Dip: 2017-2024

In [135]:
import plotly.graph_objects as go

covid_years = list(range(2017, 2025))
top_10 = df_clean.sort_values(by=2024, ascending=False).head(10)

fig = go.Figure()

# Plot each country line (same loop logic)
for index, row in top_10.iterrows():
    fig.add_trace(go.Scatter(
        x=covid_years,
        y=row[covid_years],
        mode='lines+markers',
        name=row['Country'],
        line=dict(width=2),
        marker=dict(symbol='circle')
    ))

# Highlight COVID period (axvspan equivalent)
fig.add_vrect(
    x0=2019, x1=2021,
    fillcolor='gray',
    opacity=0.15,
    line_width=0,
    annotation_text="Pandemic Impact",
    annotation_position="top left"
)

# Annotation (same relative placement logic)
y_max = top_10[covid_years].values.max()
fig.add_annotation(
    x=2020,
    y=y_max * 0.9,
    text="COVID Shock",
    showarrow=False,
    xanchor='center'
)

# Layout (size + labels + title)
fig.update_layout(
    title=dict(
        text="GDP Trends: COVID-19 Shock and Recovery (2017–2024)",
        font=dict(size=14),
        x=0.5
    ),
    xaxis_title="Year",
    yaxis_title="GDP (Current US$)",
    width=1200,
    height=700,
    template="plotly_white",
    legend=dict(
        x=1.05,
        y=1,
        font=dict(size=8)
    )
)

# Grid styling equivalent
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='rgba(0,0,0,0.2)')
fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='rgba(0,0,0,0.2)')

fig.show()

### Insights
Universal Resilience: The visualization clearly captures a sharp, synchronized dip or stagnation in GDP across all major economies in 2020, followed by a remarkably steep "V-shaped" recovery starting in 2021.

Widening Performance Gap: While all top nations recovered, the trajectories post-2021 show a widening gap, with certain economies (like the US and India) accelerating more aggressively than others during the inflationary post-pandemic period.

### Shock vs. Recovery Comparison

In [136]:
import plotly.graph_objects as go

shock_year = 2020
pre_year = 2019
post_year = 2024
top_10 = top_10.copy()

top_10['COVID_Shock_%'] = ((top_10[shock_year] - top_10[pre_year]) / top_10[pre_year].replace(0, np.nan)) * 100
top_10['Post_COVID_Avg_Growth_%'] = (((top_10[post_year] / top_10[shock_year]) ** (1/4)) - 1) * 100

plot_df = top_10.melt(
    id_vars='Country',
    value_vars=['COVID_Shock_%', 'Post_COVID_Avg_Growth_%'],
    var_name='Metric',
    value_name='Rate'
)

plot_df['Metric'] = plot_df['Metric'].replace({
    'COVID_Shock_%': '2020 Shock (vs 2019)',
    'Post_COVID_Avg_Growth_%': 'Post-COVID Avg Growth (2021–24)'
})

# Separate data for traces (same as hue split)
shock_df = plot_df[plot_df['Metric'] == '2020 Shock (vs 2019)']
growth_df = plot_df[plot_df['Metric'] == 'Post-COVID Avg Growth (2021–24)']

fig = go.Figure()

fig.add_trace(go.Bar(
    x=shock_df['Country'],
    y=shock_df['Rate'],
    name='2020 Shock (vs 2019)',
    marker=dict(color='#d9534f'),
    text=[f"{v:.1f}" for v in shock_df['Rate']],
    textposition='outside'
))

fig.add_trace(go.Bar(
    x=growth_df['Country'],
    y=growth_df['Rate'],
    name='Post-COVID Avg Growth (2021–24)',
    marker=dict(color='#5cb85c'),
    text=[f"{v:.1f}" for v in growth_df['Rate']],
    textposition='outside'
))

fig.update_layout(
    title=dict(
        text="Economic Resilience: Pandemic Shock vs Post-Pandemic Recovery",
        font=dict(size=14),
        x=0.5
    ),
    xaxis_title="Country",
    yaxis_title="Percentage Change (%)",
    barmode='group',
    width=1200,
    height=600,
    legend_title_text="Economic Phase",
    template="plotly_white"
)

# Horizontal zero line
fig.add_shape(
    type="line",
    x0=-0.5,
    x1=len(plot_df['Country'].unique()) - 0.5,
    y0=0,
    y1=0,
    line=dict(color="black", width=1)
)

# Rotate x labels
fig.update_xaxes(tickangle=-45)

# Grid styling similar to matplotlib
fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='rgba(0,0,0,0.2)')

fig.show()

### Insights
Shock vs. Resilience: The chart quantifies the immediate negative impact of the 2020 pandemic against the subsequent four-year recovery, highlighting which major economies displayed the greatest structural resilience.

Recovery Strength: While every top-10 nation faced a contraction, the varying heights of the green bars identify the "outperformers" whose post-pandemic growth significantly outpaced their initial economic losses.

---

## Extension: Structural and Comparative Indicator Preparation

The notebook now transitions from GDP-only analysis toward a broader multi-indicator framework. The next steps prepare additional macroeconomic indicators for aligned country-level and year-level comparison with GDP.

### Indicators Selected for Further Analysis

- Exports of goods and services
- Imports of goods and services
- Gross capital formation
- Final consumption expenditure
- Manufacturing (ISIC D) Value Added

In [137]:
# ---------------------------------------------
# Prepare additional indicators for extended analysis
# ---------------------------------------------
# Going back to original data to start working with other indicators
df.head()

,CountryID,Country,IndicatorName,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,4,Afghanistan,Final consumption expenditure,1.691,1.827,1.544,1.638,1.984,2.173,2.249,2.680,2.942,3.302,3.268,3.110,3.077,3.044,3.007,2.973,2.972,2.584,2.384,2.991,3.241,3.117,3.374,2.689,2.215,3.513,3.511,3.504,3.494,3.368,4.507,4.647,5.092,6.319,6.631,7.348,7.717,10.618,10.033,11.441,15.559,19.503,22.825,21.907,20.161,19.054,18.416,18.596,20.827,21.381,22.863,16.638,16.933,20.093,27.087
1,4,Afghanistan,Household consumption expenditure (including N...,1.577,1.704,1.440,1.527,1.851,2.027,2.097,2.499,2.744,3.080,3.048,2.900,2.870,2.839,2.804,2.773,2.772,2.410,2.224,2.789,3.023,2.906,3.147,2.508,2.066,3.276,3.274,3.269,3.257,3.142,4.205,4.324,4.764,5.874,6.076,6.679,6.896,9.477,8.965,9.851,12.842,16.158,18.517,17.584,15.815,14.969,14.296,14.608,16.883,17.220,18.445,13.414,13.836,16.627,22.129
2,4,Afghanistan,General government final consumption expenditure,0.114,0.123,0.104,0.110,0.134,0.147,0.152,0.181,0.198,0.223,0.220,0.210,0.207,0.205,0.203,0.200,0.200,0.174,0.161,0.202,0.219,0.210,0.228,0.181,0.149,0.237,0.237,0.236,0.237,0.226,0.302,0.323,0.328,0.445,0.555,0.669,0.822,1.141,1.068,1.590,2.717,3.345,4.307,4.323,4.346,4.085,4.120,3.988,3.944,4.161,4.418,3.224,3.097,3.466,4.958
3,4,Afghanistan,Gross capital formation,0.096,0.100,0.104,0.127,0.189,0.231,0.349,0.367,0.458,0.492,0.481,0.468,0.458,0.453,0.449,0.443,0.443,0.386,0.356,0.446,0.484,0.442,0.456,0.347,0.273,0.414,0.396,0.379,0.362,0.335,0.431,0.492,0.484,0.535,0.863,1.191,1.435,1.488,1.285,1.530,1.990,2.373,3.013,2.986,2.796,2.711,2.332,2.641,2.690,2.434,2.289,1.969,2.363,2.491,2.041
4,4,Afghanistan,Gross fixed capital formation (including Acqui...,0.096,0.100,0.104,0.127,0.189,0.231,0.349,0.367,0.458,0.492,0.481,0.468,0.458,0.453,0.449,0.443,0.443,0.386,0.356,0.446,0.484,0.442,0.456,0.347,0.273,0.414,0.396,0.379,0.362,0.335,0.431,0.492,0.484,0.535,0.863,1.191,1.435,1.488,1.285,1.530,1.990,2.373,3.013,2.986,2.796,2.711,2.332,2.641,2.690,2.434,2.289,1.969,2.363,2.491,2.041

In [138]:
print(df["IndicatorName"].unique())

['Final consumption expenditure'
 'Household consumption expenditure (including Non-profit institutions serving households)'
 'General government final consumption expenditure'
 'Gross capital formation'
 'Gross fixed capital formation (including Acquisitions less disposals of valuables)'
 'Exports of goods and services' 'Imports of goods and services'
 'Gross Domestic Product (GDP)'
 'Agriculture, hunting, forestry, fishing (ISIC A-B)'
 'Mining, Manufacturing, Utilities (ISIC C-E)' 'Manufacturing (ISIC D)'
 'Construction (ISIC F)'
 'Wholesale, retail trade, restaurants and hotels (ISIC G-H)'
 'Transport, storage and communication (ISIC I)'
 'Other Activities (ISIC J-P)' 'Total Value Added'
 'Changes in inventories']

In [139]:
selected_indicators = [
    "Exports of goods and services",
    "Imports of goods and services",
    "Gross capital formation",
    "Final consumption expenditure",
    "Manufacturing (ISIC D)"
]

selected_indicators

['Exports of goods and services',
 'Imports of goods and services',
 'Gross capital formation',
 'Final consumption expenditure',
 'Manufacturing (ISIC D)']

In [140]:
df_filtered = df[df["IndicatorName"].isin(selected_indicators)].copy()
df_filtered

,CountryID,Country,IndicatorName,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,4,Afghanistan,Final consumption expenditure,1.691,1.827,1.544,1.638,1.984,2.173,2.249,2.680,2.942,3.302,3.268,3.110,3.077,3.044,3.007,2.973,2.972,2.584,2.384,2.991,3.241,3.117,3.374,2.689,2.215,3.513,3.511,3.504,3.494,3.368,4.507,4.647,5.092,6.319,6.631,7.348,7.717,10.618,10.033,11.441,15.559,19.503,22.825,21.907,20.161,19.054,18.416,18.596,20.827,21.381,22.863,16.638,16.933,20.093,27.087
3,4,Afghanistan,Gross capital formation,0.096,0.100,0.104,0.127,0.189,0.231,0.349,0.367,0.458,0.492,0.481,0.468,0.458,0.453,0.449,0.443,0.443,0.386,0.356,0.446,0.484,0.442,0.456,0.347,0.273,0.414,0.396,0.379,0.362,0.335,0.431,0.492,0.484,0.535,0.863,1.191,1.435,1.488,1.285,1.530,1.990,2.373,3.013,2.986,2.796,2.711,2.332,2.641,2.690,2.434,2.289,1.969,2.363,2.491,2.041
5,4,Afghanistan,Exports of goods and services,0.171,0.200,0.236,0.224,0.302,0.300,0.338,0.344,0.358,0.440,0.418,0.397,0.399,0.391,0.386,0.383,0.382,0.332,0.307,0.385,0.417,0.462,0.561,0.492,0.439,0.748,0.794,0.837,0.875,0.880,1.225,1.221,1.271,2.033,1.806,1.878,2.109,2.122,2.137,2.407,2.343,2.015,2.504,3.030,3.093,3.271,3.324,4.178,2.944,2.376,2.082,2.174,2.605,2.653,1.823
6,4,Afghanistan,Imports of goods and services,0.209,0.296,0.289,0.256,0.320,0.338,0.380,0.438,0.458,0.537,0.525,0.496,0.495,0.488,0.482,0.477,0.477,0.414,0.383,0.480,0.520,0.680,0.917,0.863,0.812,1.438,1.576,1.703,1.819,1.863,2.632,2.740,2.562,3.988,3.796,3.943,3.968,4.228,3.159,3.447,4.748,5.968,8.547,8.019,6.549,6.337,5.887,6.433,7.734,6.819,7.252,5.620,7.726,8.295,12.668
10,4,Afghanistan,Manufacturing (ISIC D),0.374,0.391,0.341,0.371,0.461,0.506,0.546,0.631,0.705,0.791,0.778,0.743,0.738,0.724,0.716,0.722,0.693,0.616,0.448,0.511,0.733,0.665,0.413,0.274,0.170,0.173,0.210,0.255,0.310,0.365,0.595,0.699,0.725,0.709,0.781,0.812,0.829,1.154,1.130,0.911,1.030,1.217,1.152,0.979,0.906,0.809,0.725,0.786,1.202,1.950,1.504,1.288,1.444,1.232,1.598
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3698,716,Zimbabwe,Final consumption expenditure,1.830,2.128,2.511,3.052,3.500,3.965,4.113,4.274,4.618,5.645,7.025,8.358,9.071,8.412,6.487,7.261,7.801,8.844,9.961,10.727,11.323,10.589,9.526,7.948,8.356,8.630,10.709,11.873,7.564,7.538,7.341,7.595,8.062,7.565,7.608,7.723,7.707,7.062,7.711,10.640,12.653,14.450,19.507,20.136,20.114,24.280,26.463,29.568,35.048,36.884,31.888,33.722,38.357,42.715,44.138
3701,716,Zimbabwe,Gross capital formation,0.411,0.533,0.628,0.849,1.324,1.377,0.949,0.972,0.606,0.766,1.462,2.161,2.111,1.438,1.402,1.460,1.630,1.464,2.125,1.807,2.215,2.272,1.985,2.170,2.377,2.645,2.581,2.637,2.133,1.328,1.183,0.889,0.411,0.620,0.334,0.110,0.111,0.495,0.326,1.232,2.259,2.453,1.687,1.758,1.879,1.920,1.873,2.943,2.908,2.588,2.479,3.590,2.976,4.452,4.044
3704,716,Zimbabwe,Exports of goods and services,0.545,0.628,0.781,0.956,1.139,1.292,1.232,1.212,1.250,1.466,2.020,2.020,1.876,1.657,1.696,1.563,1.867,2.021,2.316,2.408,2.503,2.439,2.293,2.513,2.976,3.395,3.858,3.956,3.286,3.451,3.328,3.027,2.615,2.510,2.556,2.412,2.535,2.629,2.632,1.883,3.569,4.908,4.307,4.198,4.080,3.916,4.323,6.017,7.002,7.086,5.060,5.634,7.314,7.603,8.252
3705,716,Zimbabwe,Imports of goods and services,0.485,0.557,0.708,0.842,0.994,1.245,0.987,1.028,1.019,1.368,2.059,2.420,2.212,1.763,1.541,1.437,1.550,1.661,1.843,2.079,2.314,2.574,2.850,2.462,2.914,3.370,3.560,4.354,3.170,3.092,3.131,2.852,2.873,2.948,3.083,3.055,3.303,3.228,4.320,4.089,6.440,7.709,8.386,7.000,6.578,7.816,7.020,7.808,8.144,7.263,5.679,6.945,9.681,10.293,10.715
3709,716,Zimbabwe,Manufacturing (ISIC D),0.399,0.480,0.615,0.799,0.984,1.069,1.046,0.998,1.041,1.253,1.696,2.006,2.013,1.939,1.599,1.394,1.651,1.899,2.073,2.587,2.448,2.686,2.473,1.877,1.789,1.867,1.945,1.824,1.192,1.089,0.991,0.938,0.742,0.863,0.805,0.362,1.614,0.448,0.637,1.066,1.109,1.293,2.404,2.466,2.455,2.699,3.038,4.231,4.828,4.777,4.653,4.020,7.037,6.786,7.116

In [141]:
df_exports = df_filtered[df_filtered["IndicatorName"] == "Exports of goods and services"].copy()

df_imports = df_filtered[df_filtered["IndicatorName"] == "Imports of goods and services"].copy()

df_gcf = df_filtered[df_filtered["IndicatorName"] == "Gross capital formation"].copy()

df_fce = df_filtered[df_filtered["IndicatorName"] == "Final consumption expenditure"].copy()

df_manufacturing = df_filtered[df_filtered["IndicatorName"] == "Manufacturing (ISIC D)"].copy()

In [142]:
df_exports

,CountryID,Country,IndicatorName,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
5,4,Afghanistan,Exports of goods and services,0.171,0.200,0.236,0.224,0.302,0.300,0.338,0.344,0.358,0.440,0.418,0.397,0.399,0.391,0.386,0.383,0.382,0.332,0.307,0.385,0.417,0.462,0.561,0.492,0.439,0.748,0.794,0.837,0.875,0.880,1.225,1.221,1.271,2.033,1.806,1.878,2.109,2.122,2.137,2.407,2.343,2.015,2.504,3.030,3.093,3.271,3.324,4.178,2.944,2.376,2.082,2.174,2.605,2.653,1.823
22,8,Albania,Exports of goods and services,0.509,0.523,0.538,0.553,0.570,0.587,0.600,0.622,0.644,0.518,0.495,0.509,0.442,0.420,0.396,0.377,0.361,0.368,0.403,0.528,0.319,0.115,0.174,0.262,0.214,0.356,0.372,0.227,0.293,0.543,0.702,0.838,0.912,1.159,1.595,1.853,2.243,3.016,3.259,3.040,3.337,3.769,3.565,3.694,3.732,3.105,3.437,4.110,4.785,4.821,3.436,5.614,7.074,9.025,9.811
39,12,Algeria,Exports of goods and services,1.141,0.987,1.460,2.344,5.108,5.233,5.838,6.389,6.715,10.334,14.509,15.301,13.954,13.615,13.553,13.620,8.215,9.430,8.417,10.236,14.435,13.316,12.168,10.783,9.750,11.159,14.246,14.510,11.104,13.737,23.342,20.273,20.385,26.210,35.288,47.498,56.328,63.719,82.340,48.982,62.204,78.573,78.098,70.747,65.995,38.489,33.417,38.610,45.571,39.481,25.613,43.661,69.517,58.488,55.233
56,20,Andorra,Exports of goods and services,0.012,0.015,0.019,0.025,0.031,0.035,0.036,0.043,0.054,0.071,0.081,0.080,0.081,0.079,0.089,0.092,0.111,0.137,0.158,0.167,0.205,0.221,0.248,0.226,0.262,0.326,0.357,0.384,0.401,0.414,0.410,0.432,0.469,0.606,0.736,0.788,0.871,1.026,1.048,0.848,0.891,1.067,0.998,1.046,1.087,0.929,0.973,1.047,1.122,1.094,0.881,1.122,1.344,1.441,1.507
73,24,Angola,Exports of goods and services,1.348,1.422,1.456,1.778,1.995,1.459,1.426,1.543,1.710,1.906,2.420,2.612,2.275,2.379,2.677,2.997,1.966,3.228,3.482,4.170,5.299,3.993,12.609,8.365,12.417,4.953,7.115,6.835,4.579,6.834,8.057,8.620,8.569,9.676,13.781,24.309,33.347,44.707,64.244,41.587,51.493,67.949,71.825,69.550,60.869,34.428,28.300,35.598,41.389,35.180,21.004,33.286,50.120,36.961,36.886
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3636,720,Yemen Democratic (Former),Exports of goods and services,0.034,0.032,0.034,0.030,0.032,0.027,0.048,0.051,0.052,0.055,0.051,0.053,0.056,0.059,0.066,0.058,0.034,0.048,0.047,0.052,0.066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3653,890,Yugoslavia (Former),Exports of goods and services,2.547,3.039,3.239,4.385,5.852,5.907,6.480,6.991,7.884,10.580,13.069,12.768,11.933,12.795,17.681,16.193,12.779,19.970,25.856,23.898,20.898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3670,894,Zambia,Exports of goods and services,1.203,0.880,1.029,1.501,1.840,1.121,1.488,1.242,1.183,1.911,2.016,1.439,1.343,1.276,1.214,1.094,0.927,1.121,1.557,1.343,1.751,1.202,1.238,1.130,1.239,1.288,1.053,1.211,0.889,0.721,0.701,1.057,1.088,1.265,2.113,2.551,4.238,5.433,5.816,4.909,7.503,9.492,10.222,11.352,10.538,7.890,7.406,9.054,9.987,8.073,8.474,11.538,11.722,11.265,8.852
3687,836,Zanzibar,Exports of goods and services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.012,0.011,0.014,0.019,0.024,0.035,0.037,0.035,0.029,0.030,0.034,0.046,0.050,0.055,0.066,0.078,0.092,0.117,0.144,0.138,0.163,0.191,0.228,0.219,0.234,0.202,0.206,0.227,0.250,0.297,0.248,0.302,0.379,0.452,0.509
3704,716,Zimbabwe,Exports of goods and services,0.545,0.628,0.781,0.956,1.139,1.292,1.232,1.212,1.250,1.466,2.020,2.020,1.876,1.657,1.696,1.563,1.867,2.021,2.316,2.408,2.503,2.439,2.293,2.513,2.976,3.395,3.858,3.956,3.286,3.451,3.328,3.027,2.615,2.510,2.556,2.412,2.535,2.629,2.632,1.883,3.569,4.908,4.307,4.198,4.080,3.916,4.323,6.017,7.002,7.086,5.060,5.634,7.314,7.603,8.252